group 'dev.termex.bridge'
version '0.53.7'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    if (project.android.hasProperty("namespace")) {
        namespace 'dev.termex.bridge'
    }

    compileSdkVersion 33
    ndkVersion android.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 21
    }
}

apply from: "../cargokit/gradle/plugin.gradle"
cargokit {
    manifestDir = ".."
    libname = "termex_flutter_bridge"
}
