// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_request`, `build_terminal_context`, `default_model_for`, `provider_from_str`, `provider_to_str`, `redact_sensitive`, `role_from_str`, `role_to_str`, `to_kind`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TokenUsage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Create a new conversation, persist its header, and return the DTO.
Future<ConversationDto> aiCreateConversation(
        {required AiProvider provider, required String model, String? title}) =>
    TermexBridge.instance.api.crateApiAiAiCreateConversation(
        provider: provider, model: model, title: title);

/// List all stored conversations, most recent first.
/// Returns an empty list when the database is unavailable.
Future<List<ConversationDto>> aiListConversations() =>
    TermexBridge.instance.api.crateApiAiAiListConversations();

/// Delete a conversation and all its messages (cascades via FK).
Future<void> aiDeleteConversation({required String conversationId}) =>
    TermexBridge.instance.api
        .crateApiAiAiDeleteConversation(conversationId: conversationId);

/// Fetch all messages in a conversation, ordered by `created_at` ASC.
Future<List<AiMessageDto>> aiGetMessages({required String conversationId}) =>
    TermexBridge.instance.api
        .crateApiAiAiGetMessages(conversationId: conversationId);

/// Persist a user message before streaming starts. Returns the message DTO.
/// The assistant reply will be inserted separately by the streaming task
/// when the final chunk arrives.
Future<AiMessageDto> aiPersistUserMessage(
        {required String conversationId, required String content}) =>
    TermexBridge.instance.api.crateApiAiAiPersistUserMessage(
        conversationId: conversationId, content: content);

/// Persist a completed assistant reply. Callers invoke this from their
/// streaming-task finaliser once all chunks have been accumulated.
Future<AiMessageDto> aiPersistAssistantMessage(
        {required String conversationId,
        required String content,
        PlatformInt64? tokensIn,
        PlatformInt64? tokensOut}) =>
    TermexBridge.instance.api.crateApiAiAiPersistAssistantMessage(
        conversationId: conversationId,
        content: content,
        tokensIn: tokensIn,
        tokensOut: tokensOut);

/// Send a user message; streaming chunks are delivered via a polling queue
/// keyed by `conversation_id` that Dart consumes via [poll_ai_chunks].
///
/// Returns the `message_id` assigned to the assistant reply so the Dart side
/// can correlate incoming chunk events. The call returns immediately; the
/// provider request runs on a detached task until completion or cancellation.
///
/// `terminal_context` contains the last N lines from the terminal scrollback.
Future<String> aiSendMessage(
        {required String conversationId,
        required String content,
        required AiProviderConfig config,
        String? terminalContext}) =>
    TermexBridge.instance.api.crateApiAiAiSendMessage(
        conversationId: conversationId,
        content: content,
        config: config,
        terminalContext: terminalContext);

/// Poll pending stream chunks for a conversation. Each call drains the buffer.
Future<List<AiChunkDto>> pollAiChunks({required String conversationId}) =>
    TermexBridge.instance.api
        .crateApiAiPollAiChunks(conversationId: conversationId);

/// Cancel an in-progress generation for a conversation.
Future<void> aiCancelGeneration({required String conversationId}) =>
    TermexBridge.instance.api
        .crateApiAiAiCancelGeneration(conversationId: conversationId);

/// Extract shell commands from an AI reply string.
/// Returns a list of command strings found in code blocks or inline code.
Future<List<String>> aiExtractCommands({required String text}) =>
    TermexBridge.instance.api.crateApiAiAiExtractCommands(text: text);

/// Check whether a command string contains potentially dangerous patterns.
Future<bool> aiIsDangerousCommand({required String command}) =>
    TermexBridge.instance.api.crateApiAiAiIsDangerousCommand(command: command);

/// Persist a provider configuration to the `settings` table. API keys are
/// stripped from the JSON blob and pushed to the OS keychain under
/// `termex:ai:apikey:{provider}` — matching the keychain convention used
/// elsewhere for SSH credentials.
Future<void> aiSaveProviderConfig({required AiProviderConfig config}) =>
    TermexBridge.instance.api.crateApiAiAiSaveProviderConfig(config: config);

/// Load the saved provider configuration (returns None if not configured).
/// The API key is lazily loaded from the keychain on read.
Future<AiProviderConfig?> aiLoadProviderConfig(
        {required AiProvider provider}) =>
    TermexBridge.instance.api
        .crateApiAiAiLoadProviderConfig(provider: provider);

/// Verify that the given API key is valid by making a minimal API call.
///
/// Uses a default model per-provider when the saved configuration is absent.
Future<bool> aiVerifyApiKey(
        {required AiProvider provider, required String apiKey}) =>
    TermexBridge.instance.api
        .crateApiAiAiVerifyApiKey(provider: provider, apiKey: apiKey);

/// Test whether a saved provider configuration is reachable.
Future<bool> aiTestProviderConfig({required AiProvider provider}) =>
    TermexBridge.instance.api
        .crateApiAiAiTestProviderConfig(provider: provider);

/// Rename a conversation's title.
Future<void> aiRenameConversation(
        {required String conversationId, required String title}) =>
    TermexBridge.instance.api.crateApiAiAiRenameConversation(
        conversationId: conversationId, title: title);

/// Ask AI to explain a shell command.
///
/// `terminal_context` is the raw scrollback text. Sensitive lines are redacted
/// before being sent.  Returns the explanation as a plain string (non-streaming).
Future<String> aiExplainCommand(
        {required String command,
        String? terminalContext,
        required AiProviderConfig config}) =>
    TermexBridge.instance.api.crateApiAiAiExplainCommand(
        command: command, terminalContext: terminalContext, config: config);

/// Ask AI to diagnose a terminal error output.
///
/// Sensitive lines in `output` are redacted before being sent to the provider.
Future<String> aiDiagnoseError(
        {required String output,
        String? command,
        required AiProviderConfig config}) =>
    TermexBridge.instance.api.crateApiAiAiDiagnoseError(
        output: output, command: command, config: config);

/// Convert a natural-language description to a list of candidate shell commands.
Future<List<String>> aiNl2Cmd(
        {required String description,
        required String osHint,
        required AiProviderConfig config}) =>
    TermexBridge.instance.api.crateApiAiAiNl2Cmd(
        description: description, osHint: osHint, config: config);

/// Generate autocomplete suggestions for a partial command using AI.
///
/// Only called when other suggestion sources return no results (prefix length ≥ 4).
Future<List<String>> aiAutocomplete(
        {required String prefix,
        String? terminalContext,
        required AiProviderConfig config}) =>
    TermexBridge.instance.api.crateApiAiAiAutocomplete(
        prefix: prefix, terminalContext: terminalContext, config: config);

/// A streaming chunk returned during AI generation.
class AiChunkDto {
  final String conversationId;
  final String messageId;

  /// Incremental text delta.
  final String delta;

  /// Set to true on the final chunk.
  final bool done;
  final PlatformInt64? tokensIn;
  final PlatformInt64? tokensOut;
  final String? error;

  const AiChunkDto({
    required this.conversationId,
    required this.messageId,
    required this.delta,
    required this.done,
    this.tokensIn,
    this.tokensOut,
    this.error,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^
      messageId.hashCode ^
      delta.hashCode ^
      done.hashCode ^
      tokensIn.hashCode ^
      tokensOut.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiChunkDto &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          messageId == other.messageId &&
          delta == other.delta &&
          done == other.done &&
          tokensIn == other.tokensIn &&
          tokensOut == other.tokensOut &&
          error == other.error;
}

/// A single conversation message sent to / received from the AI.
class AiMessageDto {
  final String id;
  final String conversationId;
  final MessageRole role;
  final String content;
  final PlatformInt64? tokensIn;
  final PlatformInt64? tokensOut;
  final String createdAt;

  const AiMessageDto({
    required this.id,
    required this.conversationId,
    required this.role,
    required this.content,
    this.tokensIn,
    this.tokensOut,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      tokensIn.hashCode ^
      tokensOut.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          role == other.role &&
          content == other.content &&
          tokensIn == other.tokensIn &&
          tokensOut == other.tokensOut &&
          createdAt == other.createdAt;
}

/// Supported AI providers.
enum AiProvider {
  claude,
  openAi,
  ollama,
  localLlama,
  ;
}

/// Configuration for a specific AI provider.
class AiProviderConfig {
  final AiProvider provider;
  final String model;

  /// API key (stored in OS keychain; None = use keychain default).
  final String? apiKey;

  /// Custom base URL for Ollama or local llama-server.
  final String? baseUrl;

  /// Max tokens to send as context from terminal scrollback.
  final int contextLines;

  const AiProviderConfig({
    required this.provider,
    required this.model,
    this.apiKey,
    this.baseUrl,
    required this.contextLines,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      model.hashCode ^
      apiKey.hashCode ^
      baseUrl.hashCode ^
      contextLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiProviderConfig &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          model == other.model &&
          apiKey == other.apiKey &&
          baseUrl == other.baseUrl &&
          contextLines == other.contextLines;
}

/// A stored conversation header (no messages).
class ConversationDto {
  final String id;
  final AiProvider provider;
  final String model;
  final String? title;
  final String createdAt;
  final String updatedAt;

  const ConversationDto({
    required this.id,
    required this.provider,
    required this.model,
    this.title,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      title.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          provider == other.provider &&
          model == other.model &&
          title == other.title &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Role of a message in a conversation.
enum MessageRole {
  user,
  assistant,
  system,
  ;
}
