// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_alive`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Initialise the application state without unlocking SQLCipher.
///
/// Checks for a stale lock file from a previous crash, writes a new one,
/// and returns whether this is a first-time installation.
///
/// Returns `Err("AnotherInstanceRunning")` if another Termex process is live.
Future<AppInitState> initApp() =>
    TermexBridge.instance.api.crateApiAppInitApp();

/// Shut down gracefully: remove lock file and flush in-memory state.
Future<void> closeApp() => TermexBridge.instance.api.crateApiAppCloseApp();

class AppInitState {
  /// true = first run (no DB yet), false = existing DB found.
  final bool isFirstRun;

  const AppInitState({
    required this.isFirstRun,
  });

  @override
  int get hashCode => isFirstRun.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInitState &&
          runtimeType == other.runtimeType &&
          isFirstRun == other.isFirstRun;
}
