// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns all known audit-event prefixes as a sorted vector.
Future<List<String>> auditListPrefixes() =>
    TermexBridge.instance.api.crateApiAuditCatalogueAuditListPrefixes();

/// Returns every known `prefix.action` event name.
Future<List<String>> auditListKnownEvents() =>
    TermexBridge.instance.api.crateApiAuditCatalogueAuditListKnownEvents();

/// Returns `true` if `event_type` is in the known-events catalogue.
Future<bool> auditIsKnownEvent({required String eventType}) =>
    TermexBridge.instance.api
        .crateApiAuditCatalogueAuditIsKnownEvent(eventType: eventType);

/// Redacts sensitive patterns from an audit detail string before persistence.
///
/// Strips any substring that starts with a case-insensitive match of
/// `password:`, `passphrase:`, `token:`, `api_key:`, or `secret:` up to the
/// next whitespace or comma.  Everything else is preserved verbatim.
Future<String> auditRedactDetail({required String detail}) =>
    TermexBridge.instance.api
        .crateApiAuditCatalogueAuditRedactDetail(detail: detail);
