// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Serialises `payload_json` into a password-protected `.termex` file.
Future<void> backupEncryptToFile(
        {required String path,
        required String password,
        required String payloadJson}) =>
    TermexBridge.instance.api.crateApiBackupBackupEncryptToFile(
        path: path, password: password, payloadJson: payloadJson);

/// Decrypts a `.termex` file and returns the JSON payload.
Future<String> backupDecryptFromFile(
        {required String path, required String password}) =>
    TermexBridge.instance.api
        .crateApiBackupBackupDecryptFromFile(path: path, password: password);

/// Returns the magic-number + version header this binary emits, for UI
/// display on the backup settings page.
Future<String> backupFormatDescription() =>
    TermexBridge.instance.api.crateApiBackupBackupFormatDescription();
