// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Returns all contexts found in the active kubeconfig file.
Future<List<K8sContext>> cloudK8SListContexts() =>
    TermexBridge.instance.api.crateApiCloudCloudK8SListContexts();

/// Switches the active kubeconfig context to `name`.
Future<void> cloudK8SSwitchContext({required String name}) =>
    TermexBridge.instance.api.crateApiCloudCloudK8SSwitchContext(name: name);

/// Lists pods in `namespace` for the given `context`.
Future<List<K8sPod>> cloudK8SListPods(
        {required String context, required String namespace}) =>
    TermexBridge.instance.api
        .crateApiCloudCloudK8SListPods(context: context, namespace: namespace);

/// Executes `command` inside `pod` (optionally in a specific `container`) and
/// returns the combined stdout/stderr output.
Future<String> cloudK8SExec(
        {required String context,
        required String pod,
        String? container,
        required String command}) =>
    TermexBridge.instance.api.crateApiCloudCloudK8SExec(
        context: context, pod: pod, container: container, command: command);

/// Returns the list of EC2 instances that are registered with SSM in `region`.
Future<List<SsmInstance>> cloudSsmListInstances({required String region}) =>
    TermexBridge.instance.api
        .crateApiCloudCloudSsmListInstances(region: region);

/// Starts an SSM session to `instance_id` in `region`.
///
/// Returns an opaque `session_id` that can be used to attach a terminal.
Future<String> cloudSsmStartSession(
        {required String instanceId, required String region}) =>
    TermexBridge.instance.api.crateApiCloudCloudSsmStartSession(
        instanceId: instanceId, region: region);

/// Returns the list of saved ECS instance shortcuts.
Future<List<EcsFavorite>> cloudEcsListFavorites() =>
    TermexBridge.instance.api.crateApiCloudCloudEcsListFavorites();

/// Saves a new ECS instance shortcut and returns it with a generated ID.
Future<EcsFavorite> cloudEcsAddFavorite(
        {required String instanceId,
        required String name,
        required String region,
        required String endpoint}) =>
    TermexBridge.instance.api.crateApiCloudCloudEcsAddFavorite(
        instanceId: instanceId, name: name, region: region, endpoint: endpoint);

/// Deletes the ECS favourite identified by `id`.
Future<void> cloudEcsRemoveFavorite({required String id}) =>
    TermexBridge.instance.api.crateApiCloudCloudEcsRemoveFavorite(id: id);

/// Persists a cloud-provider credential bundle reference.  The real secret
/// material must live in the OS keychain under
/// `cloud:{provider}:{profile_name}`; the database row is only the index.
Future<void> cloudSaveCredential({required CloudCredential credential}) =>
    TermexBridge.instance.api
        .crateApiCloudCloudSaveCredential(credential: credential);

/// Loads the most-recently saved credential profile for `provider`, or
/// `None` if none exists.
Future<CloudCredential?> cloudLoadCredential({required String provider}) =>
    TermexBridge.instance.api
        .crateApiCloudCloudLoadCredential(provider: provider);

/// Cloud-provider credential bundle.  The actual secret material lives in the
/// OS keychain; only the opaque reference is persisted in the database.
class CloudCredential {
  /// Provider identifier, e.g. `"aws"`, `"aliyun"`, `"k8s"`.
  final String provider;

  /// Access key / client ID, if applicable.
  final String? keyId;

  /// Default region, if applicable.
  final String? region;

  const CloudCredential({
    required this.provider,
    this.keyId,
    this.region,
  });

  @override
  int get hashCode => provider.hashCode ^ keyId.hashCode ^ region.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudCredential &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          keyId == other.keyId &&
          region == other.region;
}

/// A saved Alibaba Cloud ECS instance shortcut.  Backed by the shared
/// `cloud_favorites` table with `resource_type = 'ecs'`.
class EcsFavorite {
  final String id;
  final String instanceId;
  final String name;
  final String region;
  final String endpoint;

  const EcsFavorite({
    required this.id,
    required this.instanceId,
    required this.name,
    required this.region,
    required this.endpoint,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      instanceId.hashCode ^
      name.hashCode ^
      region.hashCode ^
      endpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EcsFavorite &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          instanceId == other.instanceId &&
          name == other.name &&
          region == other.region &&
          endpoint == other.endpoint;
}

/// A kubeconfig context entry.
class K8sContext {
  final String name;
  final String cluster;
  final String namespace;

  /// Whether this is the currently active kubeconfig context.
  final bool isActive;

  const K8sContext({
    required this.name,
    required this.cluster,
    required this.namespace,
    required this.isActive,
  });

  @override
  int get hashCode =>
      name.hashCode ^ cluster.hashCode ^ namespace.hashCode ^ isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is K8sContext &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          cluster == other.cluster &&
          namespace == other.namespace &&
          isActive == other.isActive;
}

/// A Kubernetes pod summary.
class K8sPod {
  final String name;
  final String namespace;

  /// Pod phase string (e.g. `"Running"`, `"Pending"`, `"Failed"`).
  final String status;

  /// Whether the pod's containers are all ready.
  final bool ready;

  /// Time since the pod was created, in seconds.
  final PlatformInt64 ageSeconds;

  const K8sPod({
    required this.name,
    required this.namespace,
    required this.status,
    required this.ready,
    required this.ageSeconds,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      namespace.hashCode ^
      status.hashCode ^
      ready.hashCode ^
      ageSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is K8sPod &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          namespace == other.namespace &&
          status == other.status &&
          ready == other.ready &&
          ageSeconds == other.ageSeconds;
}

/// An AWS EC2 instance reachable via AWS Systems Manager Session Manager.
class SsmInstance {
  final String instanceId;

  /// Human-readable Name tag, if set.
  final String? name;

  /// Instance state string (e.g. `"running"`, `"stopped"`).
  final String state;
  final String region;

  const SsmInstance({
    required this.instanceId,
    this.name,
    required this.state,
    required this.region,
  });

  @override
  int get hashCode =>
      instanceId.hashCode ^ name.hashCode ^ state.hashCode ^ region.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SsmInstance &&
          runtimeType == other.runtimeType &&
          instanceId == other.instanceId &&
          name == other.name &&
          state == other.state &&
          region == other.region;
}
