// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Verify the master password by attempting to open the database.
///
/// Returns `Ok(true)` on success, `Ok(false)` if the password is wrong,
/// or `Err(...)` if the database is corrupt or unreadable for another reason.
Future<bool> verifyMasterPassword({required String password}) =>
    TermexBridge.instance.api
        .crateApiCryptoVerifyMasterPassword(password: password);

/// Unlock the database with a master password.
///
/// On success the global DB singleton is set so subsequent API calls work.
Future<void> unlockDatabase({required String password}) =>
    TermexBridge.instance.api.crateApiCryptoUnlockDatabase(password: password);
