// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'daemon.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `empty`, `event_queues`, `from_server_message`, `get_client`, `handles`, `map_err`, `ssh_exec_capture`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// Connect to a termexd WebSocket and register the resulting client
/// in the handle map. Returns the handle id Dart should pass to
/// later calls. Always succeeds with a fresh id; the underlying
/// connect happens lazily inside the resulting client task.
Future<String> daemonConnect({required String wsUrl, required String token}) =>
    TermexBridge.instance.api
        .crateApiDaemonDaemonConnect(wsUrl: wsUrl, token: token);

/// Close a daemon connection and drop its handle.
Future<void> daemonDisconnect({required String handleId}) =>
    TermexBridge.instance.api
        .crateApiDaemonDaemonDisconnect(handleId: handleId);

Future<String> daemonTaskAssign(
        {required String handleId,
        required AiCliKindDto aiCli,
        required String prompt,
        String? workdir,
        required int idleTimeoutSec,
        String? serverId}) =>
    TermexBridge.instance.api.crateApiDaemonDaemonTaskAssign(
        handleId: handleId,
        aiCli: aiCli,
        prompt: prompt,
        workdir: workdir,
        idleTimeoutSec: idleTimeoutSec,
        serverId: serverId);

Future<List<TaskDto>> daemonTaskList(
        {required String handleId, TaskStatusDto? status}) =>
    TermexBridge.instance.api
        .crateApiDaemonDaemonTaskList(handleId: handleId, status: status);

Future<TaskDto?> daemonTaskGet(
        {required String handleId, required String taskId}) =>
    TermexBridge.instance.api
        .crateApiDaemonDaemonTaskGet(handleId: handleId, taskId: taskId);

Future<void> daemonTaskCancel(
        {required String handleId,
        required String taskId,
        required String signal}) =>
    TermexBridge.instance.api.crateApiDaemonDaemonTaskCancel(
        handleId: handleId, taskId: taskId, signal: signal);

/// Begin streaming a task's events into the per-handle event queue.
/// Calling repeatedly with the same `(handle, task_id)` is a no-op
/// (we keep the existing pump task alive).
Future<void> daemonSubscribe(
        {required String handleId, required String taskId}) =>
    TermexBridge.instance.api
        .crateApiDaemonDaemonSubscribe(handleId: handleId, taskId: taskId);

/// Drain accumulated events for a handle. Returns up to
/// `max_events` (caller can pass 0 for "all"). Events are returned
/// in arrival order and removed from the queue.
Future<List<DaemonEvent>> daemonDrainEvents(
        {required String handleId, required int maxEvents}) =>
    TermexBridge.instance.api.crateApiDaemonDaemonDrainEvents(
        handleId: handleId, maxEvents: maxEvents);

/// Probe a remote machine for a `termexd` binary by running
/// `which termexd && termexd --version` over an SSH session the
/// Dart side has already opened (via `open_ssh_session`).
///
/// Returns the version string for `Available`, `NotInstalled` if
/// `which` fails, or `Error(msg)` for transport problems.
Future<DaemonProbeDto> daemonProbe({required String sshSessionId}) =>
    TermexBridge.instance.api
        .crateApiDaemonDaemonProbe(sshSessionId: sshSessionId);

/// Read the daemon's bearer token from the remote machine over an
/// existing SSH session. Returns the trimmed token.
///
/// The Dart side composes this with `port_forward_start` (local →
/// remote 127.0.0.1:7821) and then `daemon_connect(ws_url, token)`.
Future<String> daemonReadToken({required String sshSessionId}) =>
    TermexBridge.instance.api
        .crateApiDaemonDaemonReadToken(sshSessionId: sshSessionId);

/// Compose the canonical client-side WebSocket URL for a port that
/// the Dart side has already forwarded to remote 127.0.0.1:7821.
Future<String> daemonWsUrlForLocalPort({required int localPort}) =>
    TermexBridge.instance.api
        .crateApiDaemonDaemonWsUrlForLocalPort(localPort: localPort);

/// SSH-tunnel-aware convenience: assumes the Dart side has already
/// established the SSH chain and a local port forward (local_port →
/// remote 127.0.0.1:7821) via the existing bridge APIs. This call
/// reads the token over SSH and then runs `daemon_connect`.
///
/// Returns the daemon handle id.
Future<String> daemonConnectViaSsh(
        {required String sshSessionId, required int localPort}) =>
    TermexBridge.instance.api.crateApiDaemonDaemonConnectViaSsh(
        sshSessionId: sshSessionId, localPort: localPort);

/// Mirror of `termex_core::task::AiCliKind` with the snake_case
/// wire labels the Dart side already uses (see v0.72.0 task UI).
enum AiCliKindDto {
  claudeCode,
  codex,
  aider,
  generic,
  ;
}

/// Tagged event the Dart side drains. Keep variants flat (no
/// discriminator union) — FRB tagged enums are still imperfect.
///
/// `kind` discriminator (Dart pattern-matches on it):
/// - `output` — raw PTY chunk
/// - `status` — terminal lifecycle change
/// - `progress` — MCP progress (v0.71.1+)
/// - `tool_use` — MCP tool-use trace (v0.71.1+)
/// - `artifact` — MCP structured artifact (v0.71.1+)
/// - `awaiting_input` — MCP wait-for-input prompt (v0.71.1+)
/// - `usage` — MCP token / cost report (v0.71.1+)
class DaemonEvent {
  final String kind;
  final String taskId;
  final BigInt? seq;
  final BigInt tsMs;
  final String? data;
  final String? stream;
  final TaskStatusDto? status;
  final int? exitCode;
  final BigInt? durationMs;
  final double? progressRatio;
  final String? progressNote;
  final String? tool;
  final String? toolStage;
  final String? toolInputSummary;
  final String? toolOutputSummary;
  final String? artifactId;
  final String? artifactKind;

  /// JSON-encoded payload (serialize/parse on the Dart side).
  final String? artifactPayloadJson;
  final String? awaitingPrompt;

  /// JSON-encoded schema (or None).
  final String? awaitingSchemaJson;
  final BigInt? usageInputTokens;
  final BigInt? usageOutputTokens;
  final String? usageModel;
  final double? usageEstimatedCostUsd;

  const DaemonEvent({
    required this.kind,
    required this.taskId,
    this.seq,
    required this.tsMs,
    this.data,
    this.stream,
    this.status,
    this.exitCode,
    this.durationMs,
    this.progressRatio,
    this.progressNote,
    this.tool,
    this.toolStage,
    this.toolInputSummary,
    this.toolOutputSummary,
    this.artifactId,
    this.artifactKind,
    this.artifactPayloadJson,
    this.awaitingPrompt,
    this.awaitingSchemaJson,
    this.usageInputTokens,
    this.usageOutputTokens,
    this.usageModel,
    this.usageEstimatedCostUsd,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      taskId.hashCode ^
      seq.hashCode ^
      tsMs.hashCode ^
      data.hashCode ^
      stream.hashCode ^
      status.hashCode ^
      exitCode.hashCode ^
      durationMs.hashCode ^
      progressRatio.hashCode ^
      progressNote.hashCode ^
      tool.hashCode ^
      toolStage.hashCode ^
      toolInputSummary.hashCode ^
      toolOutputSummary.hashCode ^
      artifactId.hashCode ^
      artifactKind.hashCode ^
      artifactPayloadJson.hashCode ^
      awaitingPrompt.hashCode ^
      awaitingSchemaJson.hashCode ^
      usageInputTokens.hashCode ^
      usageOutputTokens.hashCode ^
      usageModel.hashCode ^
      usageEstimatedCostUsd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DaemonEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          taskId == other.taskId &&
          seq == other.seq &&
          tsMs == other.tsMs &&
          data == other.data &&
          stream == other.stream &&
          status == other.status &&
          exitCode == other.exitCode &&
          durationMs == other.durationMs &&
          progressRatio == other.progressRatio &&
          progressNote == other.progressNote &&
          tool == other.tool &&
          toolStage == other.toolStage &&
          toolInputSummary == other.toolInputSummary &&
          toolOutputSummary == other.toolOutputSummary &&
          artifactId == other.artifactId &&
          artifactKind == other.artifactKind &&
          artifactPayloadJson == other.artifactPayloadJson &&
          awaitingPrompt == other.awaitingPrompt &&
          awaitingSchemaJson == other.awaitingSchemaJson &&
          usageInputTokens == other.usageInputTokens &&
          usageOutputTokens == other.usageOutputTokens &&
          usageModel == other.usageModel &&
          usageEstimatedCostUsd == other.usageEstimatedCostUsd;
}

@freezed
sealed class DaemonProbeDto with _$DaemonProbeDto {
  const DaemonProbeDto._();

  const factory DaemonProbeDto.available(
    String field0,
  ) = DaemonProbeDto_Available;
  const factory DaemonProbeDto.notInstalled() = DaemonProbeDto_NotInstalled;
  const factory DaemonProbeDto.error(
    String field0,
  ) = DaemonProbeDto_Error;
}

class TaskDto {
  final String id;
  final AiCliKindDto aiCliKind;
  final String prompt;
  final String? workdir;
  final TaskStatusDto status;
  final String startedAt;
  final String? endedAt;
  final int? exitCode;
  final int idleTimeoutSec;
  final String? outputTail;
  final String? error;

  const TaskDto({
    required this.id,
    required this.aiCliKind,
    required this.prompt,
    this.workdir,
    required this.status,
    required this.startedAt,
    this.endedAt,
    this.exitCode,
    required this.idleTimeoutSec,
    this.outputTail,
    this.error,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      aiCliKind.hashCode ^
      prompt.hashCode ^
      workdir.hashCode ^
      status.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode ^
      exitCode.hashCode ^
      idleTimeoutSec.hashCode ^
      outputTail.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          aiCliKind == other.aiCliKind &&
          prompt == other.prompt &&
          workdir == other.workdir &&
          status == other.status &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt &&
          exitCode == other.exitCode &&
          idleTimeoutSec == other.idleTimeoutSec &&
          outputTail == other.outputTail &&
          error == other.error;
}

/// Mirror of `termex_core::task::TaskStatus`.
enum TaskStatusDto {
  pending,
  pendingConfirmation,
  running,
  succeeded,
  failed,
  cancelled,
  ;
}
