// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Classify a single probe outcome. The Dart side calls this after
/// it has already run the SSH probe and learned which bucket the
/// outcome falls into.
///
/// `outcome` is one of: `"handshake_ok"`, `"not_reachable"`,
/// `"binary_missing"`, `"protocol_error"`. For `handshake_ok` the
/// `version` parameter is required; otherwise it is ignored.
Future<DesktopDaemonProbeDto> desktopProbeClassify(
        {required String outcome, String? version}) =>
    TermexBridge.instance.api.crateApiDesktopProbeDesktopProbeClassify(
        outcome: outcome, version: version);

/// Fold a batch of per-server results into the summary used by the
/// MissingDaemonsBanner widget.
Future<ProbeBatchSummaryDto> desktopProbeSummary(
        {required List<ServerProbeResultDto> results}) =>
    TermexBridge.instance.api
        .crateApiDesktopProbeDesktopProbeSummary(results: results);

/// Constant the Dart side can read so the UI labels stay in sync
/// with whatever the Rust core requires.
Future<String> desktopProbeMinVersion() =>
    TermexBridge.instance.api.crateApiDesktopProbeDesktopProbeMinVersion();

/// Mirror of `termex_core::desktop::probe::DaemonProbe` flattened
/// for the FRB wire (Dart doesn't get the tagged enum directly —
/// flatten avoids a wrapper class).
class DesktopDaemonProbeDto {
  /// "available" / "not_installed" / "unreachable" / "outdated" / "protocol_error".
  final String kind;

  /// Populated only for Available / Outdated.
  final String? version;

  /// Populated only for Outdated.
  final String? minVersion;

  const DesktopDaemonProbeDto({
    required this.kind,
    this.version,
    this.minVersion,
  });

  @override
  int get hashCode => kind.hashCode ^ version.hashCode ^ minVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DesktopDaemonProbeDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          version == other.version &&
          minVersion == other.minVersion;
}

class ProbeBatchSummaryDto {
  final int total;
  final int available;
  final int notInstalled;
  final int unreachable;
  final int outdated;
  final int protocolError;
  final bool anyAvailable;

  const ProbeBatchSummaryDto({
    required this.total,
    required this.available,
    required this.notInstalled,
    required this.unreachable,
    required this.outdated,
    required this.protocolError,
    required this.anyAvailable,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      available.hashCode ^
      notInstalled.hashCode ^
      unreachable.hashCode ^
      outdated.hashCode ^
      protocolError.hashCode ^
      anyAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProbeBatchSummaryDto &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          available == other.available &&
          notInstalled == other.notInstalled &&
          unreachable == other.unreachable &&
          outdated == other.outdated &&
          protocolError == other.protocolError &&
          anyAvailable == other.anyAvailable;
}

class ServerProbeResultDto {
  final String serverId;
  final DesktopDaemonProbeDto probe;

  const ServerProbeResultDto({
    required this.serverId,
    required this.probe,
  });

  @override
  int get hashCode => serverId.hashCode ^ probe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerProbeResultDto &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          probe == other.probe;
}
