// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `as_str`, `from_str`

Future<GitSyncStatus> gitSyncStatus({required String serverId}) =>
    TermexBridge.instance.api.crateApiGitSyncGitSyncStatus(serverId: serverId);

Future<void> gitSyncEnable(
        {required String serverId,
        required String remote,
        required String localPath}) =>
    TermexBridge.instance.api.crateApiGitSyncGitSyncEnable(
        serverId: serverId, remote: remote, localPath: localPath);

Future<void> gitSyncDisable({required String serverId}) =>
    TermexBridge.instance.api.crateApiGitSyncGitSyncDisable(serverId: serverId);

Future<GitSyncStatus> gitSyncTrigger({required String serverId}) =>
    TermexBridge.instance.api.crateApiGitSyncGitSyncTrigger(serverId: serverId);

Future<List<GitSyncRepo>> gitSyncListRepos({required String serverId}) =>
    TermexBridge.instance.api
        .crateApiGitSyncGitSyncListRepos(serverId: serverId);

Future<String> gitSyncAddRepo({required GitSyncInput input}) =>
    TermexBridge.instance.api.crateApiGitSyncGitSyncAddRepo(input: input);

Future<void> gitSyncRemoveRepo({required String id}) =>
    TermexBridge.instance.api.crateApiGitSyncGitSyncRemoveRepo(id: id);

Future<void> gitSyncUpdateRepoMode(
        {required String id, required GitSyncMode mode}) =>
    TermexBridge.instance.api
        .crateApiGitSyncGitSyncUpdateRepoMode(id: id, mode: mode);

Future<void> gitSyncRecordSyncResult({required String id, String? error}) =>
    TermexBridge.instance.api
        .crateApiGitSyncGitSyncRecordSyncResult(id: id, error: error);

enum GitSyncHealth {
  synced,
  pushing,
  pulling,
  conflict,
  error,
  disabled,
  ;
}

class GitSyncInput {
  final String serverId;
  final String localPath;
  final String remoteUrl;
  final GitSyncMode syncMode;

  const GitSyncInput({
    required this.serverId,
    required this.localPath,
    required this.remoteUrl,
    required this.syncMode,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      localPath.hashCode ^
      remoteUrl.hashCode ^
      syncMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitSyncInput &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          localPath == other.localPath &&
          remoteUrl == other.remoteUrl &&
          syncMode == other.syncMode;
}

enum GitSyncMode {
  notify,
  auto,
  manual,
  ;
}

class GitSyncRepo {
  final String id;
  final String serverId;
  final String localPath;
  final String remoteUrl;
  final GitSyncMode syncMode;
  final String? lastSyncAt;
  final String? lastError;

  const GitSyncRepo({
    required this.id,
    required this.serverId,
    required this.localPath,
    required this.remoteUrl,
    required this.syncMode,
    this.lastSyncAt,
    this.lastError,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      serverId.hashCode ^
      localPath.hashCode ^
      remoteUrl.hashCode ^
      syncMode.hashCode ^
      lastSyncAt.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitSyncRepo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          serverId == other.serverId &&
          localPath == other.localPath &&
          remoteUrl == other.remoteUrl &&
          syncMode == other.syncMode &&
          lastSyncAt == other.lastSyncAt &&
          lastError == other.lastError;
}

class GitSyncStatus {
  final String serverId;
  final bool enabled;
  final GitSyncHealth health;
  final GitSyncMode mode;
  final String localPath;
  final String remoteUrl;
  final String? lastSyncAt;
  final String? lastError;
  final int ahead;
  final int behind;
  final List<String> conflicts;

  const GitSyncStatus({
    required this.serverId,
    required this.enabled,
    required this.health,
    required this.mode,
    required this.localPath,
    required this.remoteUrl,
    this.lastSyncAt,
    this.lastError,
    required this.ahead,
    required this.behind,
    required this.conflicts,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      enabled.hashCode ^
      health.hashCode ^
      mode.hashCode ^
      localPath.hashCode ^
      remoteUrl.hashCode ^
      lastSyncAt.hashCode ^
      lastError.hashCode ^
      ahead.hashCode ^
      behind.hashCode ^
      conflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitSyncStatus &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          enabled == other.enabled &&
          health == other.health &&
          mode == other.mode &&
          localPath == other.localPath &&
          remoteUrl == other.remoteUrl &&
          lastSyncAt == other.lastSyncAt &&
          lastError == other.lastError &&
          ahead == other.ahead &&
          behind == other.behind &&
          conflicts == other.conflicts;
}
