// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Lists all server groups ordered by `sort_order`.
Future<List<GroupDto>> listGroups() =>
    TermexBridge.instance.api.crateApiGroupListGroups();

/// Returns a single group by ID, or `None` if not found.
Future<GroupDto?> getGroup({required String id}) =>
    TermexBridge.instance.api.crateApiGroupGetGroup(id: id);

/// Creates a new server group, returning the created group.
Future<GroupDto> createGroup({required GroupInput input}) =>
    TermexBridge.instance.api.crateApiGroupCreateGroup(input: input);

/// Updates an existing server group by ID, returning the updated group.
Future<GroupDto> updateGroup({required String id, required GroupInput input}) =>
    TermexBridge.instance.api.crateApiGroupUpdateGroup(id: id, input: input);

/// Deletes a group by ID and NULLifies `group_id` on servers that belonged to it.
Future<void> deleteGroup({required String id}) =>
    TermexBridge.instance.api.crateApiGroupDeleteGroup(id: id);

/// Updates the `sort_order` of each group according to the provided ordered list of IDs.
///
/// The first ID in `ids` receives `sort_order = 0`, the second receives `1`, and so on.
Future<void> reorderGroups({required List<String> ids}) =>
    TermexBridge.instance.api.crateApiGroupReorderGroups(ids: ids);

/// Server group data transfer object exposed to Flutter.
class GroupDto {
  final String id;
  final String name;
  final String color;
  final String icon;
  final String? parentId;
  final int sortOrder;
  final String createdAt;
  final String updatedAt;

  const GroupDto({
    required this.id,
    required this.name,
    required this.color,
    required this.icon,
    this.parentId,
    required this.sortOrder,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      color.hashCode ^
      icon.hashCode ^
      parentId.hashCode ^
      sortOrder.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          color == other.color &&
          icon == other.icon &&
          parentId == other.parentId &&
          sortOrder == other.sortOrder &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Input payload for creating or updating a server group.
class GroupInput {
  final String name;
  final String color;
  final String icon;
  final String? parentId;
  final int sortOrder;

  const GroupInput({
    required this.name,
    required this.color,
    required this.icon,
    this.parentId,
    required this.sortOrder,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      color.hashCode ^
      icon.hashCode ^
      parentId.hashCode ^
      sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          color == other.color &&
          icon == other.icon &&
          parentId == other.parentId &&
          sortOrder == other.sortOrder;
}
