// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dto_to_device`, `ensure_schema`, `push_platform_str`, `sql_box`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Upsert a device — used by the mobile shell's "register on
/// connect" path and the settings page's "rename this device".
Future<void> handoffUpsertDevice({required DeviceDto dto}) =>
    TermexBridge.instance.api.crateApiHandoffHandoffUpsertDevice(dto: dto);

/// Heartbeat — refreshes only `last_seen_at`. Cheap; called
/// per-frame by the daemon client.
Future<void> handoffTouchDevice(
        {required String deviceId, required String nowRfc3339}) =>
    TermexBridge.instance.api.crateApiHandoffHandoffTouchDevice(
        deviceId: deviceId, nowRfc3339: nowRfc3339);

Future<DeviceDto?> handoffGetDevice({required String deviceId}) =>
    TermexBridge.instance.api
        .crateApiHandoffHandoffGetDevice(deviceId: deviceId);

/// All known devices, most-recently-seen first. UI maps to
/// DeviceSummaryDto when rendering watcher chips.
Future<List<DeviceDto>> handoffListDevices() =>
    TermexBridge.instance.api.crateApiHandoffHandoffListDevices();

Future<void> handoffDeleteDevice({required String deviceId}) =>
    TermexBridge.instance.api
        .crateApiHandoffHandoffDeleteDevice(deviceId: deviceId);

/// Drop devices not seen since `cutoff_rfc3339` (typ. now - 90d).
/// Returns the row count removed.
Future<int> handoffPruneStale({required String cutoffRfc3339}) =>
    TermexBridge.instance.api
        .crateApiHandoffHandoffPruneStale(cutoffRfc3339: cutoffRfc3339);

class DeviceDto {
  final String id;
  final String name;

  /// "ios" / "android" / "macos" / "linux" / "windows".
  final String platform;
  final String firstSeenAt;
  final String lastSeenAt;

  /// Push token kept opaque to the Dart side — never log.
  final String? pushToken;

  /// "ios_apns" / "android_fcm" or null.
  final String? pushPlatform;

  const DeviceDto({
    required this.id,
    required this.name,
    required this.platform,
    required this.firstSeenAt,
    required this.lastSeenAt,
    this.pushToken,
    this.pushPlatform,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      platform.hashCode ^
      firstSeenAt.hashCode ^
      lastSeenAt.hashCode ^
      pushToken.hashCode ^
      pushPlatform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          platform == other.platform &&
          firstSeenAt == other.firstSeenAt &&
          lastSeenAt == other.lastSeenAt &&
          pushToken == other.pushToken &&
          pushPlatform == other.pushPlatform;
}
