// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_conflict`, `load_overrides`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Returns the effective keybindings: user overrides merged on top of defaults.
Future<List<KeybindingEntry>> keybindingList() =>
    TermexBridge.instance.api.crateApiKeybindingsKeybindingList();

/// Sets a custom key combination for `action`.
Future<void> keybindingSet(
        {required String action,
        required String keyCombination,
        required String context}) =>
    TermexBridge.instance.api.crateApiKeybindingsKeybindingSet(
        action: action, keyCombination: keyCombination, context: context);

/// Resets a single action's binding to its default (removes user override).
Future<void> keybindingReset({required String action}) =>
    TermexBridge.instance.api
        .crateApiKeybindingsKeybindingReset(action: action);

/// Resets all keybindings to their defaults by clearing all user overrides.
Future<void> keybindingResetAll() =>
    TermexBridge.instance.api.crateApiKeybindingsKeybindingResetAll();

/// Checks whether `key_combination` in `context` conflicts with an existing binding.
///
/// A conflict exists when the same combination is already used by a *different* action
/// in the same context or in the `"global"` context.  Returns the conflicting action's
/// info, or `None` if no conflict exists.
Future<ConflictInfo?> keybindingCheckConflict(
        {required String keyCombination, required String context}) =>
    TermexBridge.instance.api.crateApiKeybindingsKeybindingCheckConflict(
        keyCombination: keyCombination, context: context);

/// Returns the hardcoded default keybindings shipped with Termex.
Future<List<KeybindingEntry>> keybindingGetDefaults() =>
    TermexBridge.instance.api.crateApiKeybindingsKeybindingGetDefaults();

/// For tests: clears the in-memory registry.  Database-backed overrides are
/// unaffected — integration tests that use the database must rely on the
/// per-test temp-directory isolation.
Future<void> testClearRegistry() =>
    TermexBridge.instance.api.crateApiKeybindingsTestClearRegistry();

/// Returns the canonical list of valid scope names.
Future<List<String>> keybindingListScopes() =>
    TermexBridge.instance.api.crateApiKeybindingsKeybindingListScopes();

/// Returns `true` if the scope is recognised.
Future<bool> keybindingIsValidScope({required String scope}) =>
    TermexBridge.instance.api
        .crateApiKeybindingsKeybindingIsValidScope(scope: scope);

/// Returns `true` if `key_combination` is a system-reserved shortcut and must
/// not be overridden.
Future<bool> keybindingIsReserved({required String keyCombination}) =>
    TermexBridge.instance.api.crateApiKeybindingsKeybindingIsReserved(
        keyCombination: keyCombination);

/// Lists every system-reserved key combination.  Used by the UI to populate
/// a warning banner in the keybinding editor.
Future<List<String>> keybindingListReservedKeys() =>
    TermexBridge.instance.api.crateApiKeybindingsKeybindingListReservedKeys();

/// Like `keybinding_set`, but rejects system-reserved combinations up-front.
Future<void> keybindingSetValidated(
        {required String action,
        required String keyCombination,
        required String context}) =>
    TermexBridge.instance.api.crateApiKeybindingsKeybindingSetValidated(
        action: action, keyCombination: keyCombination, context: context);

/// Describes a conflict with an existing keybinding.
class ConflictInfo {
  final String action;
  final String keyCombination;

  const ConflictInfo({
    required this.action,
    required this.keyCombination,
  });

  @override
  int get hashCode => action.hashCode ^ keyCombination.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictInfo &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          keyCombination == other.keyCombination;
}

/// A single keyboard shortcut binding.
class KeybindingEntry {
  final String action;
  final String keyCombination;

  /// One of `"global"`, `"terminal"`, or `"sftp"`.
  final String context;

  const KeybindingEntry({
    required this.action,
    required this.keyCombination,
    required this.context,
  });

  @override
  int get hashCode =>
      action.hashCode ^ keyCombination.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeybindingEntry &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          keyCombination == other.keyCombination &&
          context == other.context;
}
