// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ModelDownloadProgress`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Start the local AI server with the given model.
/// Returns immediately; use [local_ai_health] to poll readiness.
///
/// `port` is accepted for API compatibility but ignored — the underlying
/// `LlamaServerState` auto-allocates a free port in the 15000–16000 range
/// to avoid conflicts with the legacy Tauri product. Callers can read the
/// actual port via [local_ai_health] after startup.
Future<void> localAiStart({required String modelId, required int port}) =>
    TermexBridge.instance.api
        .crateApiLocalAiLocalAiStart(modelId: modelId, port: port);

/// Stop the local AI server process.
Future<void> localAiStop() =>
    TermexBridge.instance.api.crateApiLocalAiLocalAiStop();

/// Query the current health of the local AI server.
///
/// Uses the shared PID file written by termex-core to locate a running
/// llama-server instance (possibly started by the legacy Tauri product),
/// then probes its port for TCP readiness. Does not issue HTTP traffic —
/// the Dart layer can do that if richer telemetry is required.
Future<LocalAiHealth> localAiHealth() =>
    TermexBridge.instance.api.crateApiLocalAiLocalAiHealth();

/// Bundled catalogue of downloadable models, enriched with the current
/// local download state.
///
/// Catalogue data is static (the set of curated models we ship) and is
/// defined inline — there is no server-side catalogue to fetch. For each
/// entry we probe `app_data_dir/models/{id}.gguf` to mark it
/// `is_downloaded`.
Future<List<LocalModelDto>> localAiListModels() =>
    TermexBridge.instance.api.crateApiLocalAiLocalAiListModels();

/// Start downloading a model and block until completion (or cancellation).
///
/// Runs HTTP range-aware download from the curated catalog URL into
/// `<data_dir>/models/<id>.gguf`. On failure the primary URL is retried once
/// against the configured mirror URL. Progress is not yet streamed through
/// FRB (that lands with the `StreamSink`-based emitter in a follow-up); the
/// Dart layer should call this and drive its own progress UI from an adjacent
/// polling timer or treat the call as atomic.
///
/// Use [local_ai_cancel_download] to abort an in-flight download.
Future<void> localAiDownloadModel({required String modelId}) =>
    TermexBridge.instance.api
        .crateApiLocalAiLocalAiDownloadModel(modelId: modelId);

/// Delete a downloaded model from disk.
///
/// Looks up the canonical model filename in `app_data_dir/models/` and
/// unlinks it. Missing files are treated as successful (idempotent delete).
Future<void> localAiDeleteModel({required String modelId}) =>
    TermexBridge.instance.api
        .crateApiLocalAiLocalAiDeleteModel(modelId: modelId);

/// Cancel an in-progress model download.
Future<void> localAiCancelDownload({required String modelId}) =>
    TermexBridge.instance.api
        .crateApiLocalAiLocalAiCancelDownload(modelId: modelId);

/// Return the base URL for the local AI server, auto-detected from the
/// PID file written by termex-core when the server is running. Falls back
/// to the conventional `127.0.0.1:8080` when no server is active.
Future<String> localAiBaseUrl() =>
    TermexBridge.instance.api.crateApiLocalAiLocalAiBaseUrl();

/// Return available disk space in bytes at the app data directory.
/// Used to warn the user before starting a large model download.
///
/// If the platform-specific check in `termex_core::local_ai::storage` is
/// unavailable (the current placeholder returns `None`), we report a
/// conservative 20 GB so the UI can continue without a hard-fail. A future
/// tech-debt item will wire `fs2::available_space` across platforms.
Future<BigInt> localAiCheckDiskSpace() =>
    TermexBridge.instance.api.crateApiLocalAiLocalAiCheckDiskSpace();

/// Cancel the pending or in-progress auto-start of the local AI server.
///
/// Called when the user disables the "auto-start on launch" setting while
/// Termex is starting up. Sets an atomic flag that the auto-start coroutine
/// (owned by the Flutter layer) must check before each step.
Future<void> localAiCancelAutoStart() =>
    TermexBridge.instance.api.crateApiLocalAiLocalAiCancelAutoStart();

/// Returns true when the auto-start sequence should abort.
/// The Flutter auto-start coroutine polls this before each expensive step.
Future<bool> localAiAutoStartIsCancelled() =>
    TermexBridge.instance.api.crateApiLocalAiLocalAiAutoStartIsCancelled();

/// Reset the auto-start cancellation flag; call at the start of each launch
/// sequence before polling [local_ai_auto_start_is_cancelled].
Future<void> localAiAutoStartReset() =>
    TermexBridge.instance.api.crateApiLocalAiLocalAiAutoStartReset();

/// Health report from the running local AI server.
class LocalAiHealth {
  final LocalAiStatus status;

  /// Currently loaded model ID, if any.
  final String? loadedModel;

  /// Memory usage in MB.
  final BigInt? memoryMb;

  /// Listening port.
  final int port;

  const LocalAiHealth({
    required this.status,
    this.loadedModel,
    this.memoryMb,
    required this.port,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      loadedModel.hashCode ^
      memoryMb.hashCode ^
      port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalAiHealth &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          loadedModel == other.loadedModel &&
          memoryMb == other.memoryMb &&
          port == other.port;
}

/// Status of the local AI server process.
enum LocalAiStatus {
  /// Server process is not running.
  stopped,

  /// Server is starting up.
  starting,

  /// Server is running and responding to health checks.
  running,

  /// Server crashed or failed to start.
  error,
  ;
}

/// A downloadable model entry.
class LocalModelDto {
  final String id;
  final String name;
  final String description;

  /// Size in bytes.
  final BigInt sizeBytes;

  /// Formatted size string (e.g. "3.8 GB").
  final String sizeLabel;
  final String quantization;

  /// Whether the model is already downloaded locally.
  final bool isDownloaded;

  /// Local file path, if downloaded.
  final String? localPath;

  const LocalModelDto({
    required this.id,
    required this.name,
    required this.description,
    required this.sizeBytes,
    required this.sizeLabel,
    required this.quantization,
    required this.isDownloaded,
    this.localPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      sizeBytes.hashCode ^
      sizeLabel.hashCode ^
      quantization.hashCode ^
      isDownloaded.hashCode ^
      localPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalModelDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          sizeBytes == other.sizeBytes &&
          sizeLabel == other.sizeLabel &&
          quantization == other.quantization &&
          isDownloaded == other.isDownloaded &&
          localPath == other.localPath;
}
