// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mobile authentication and lifecycle management stubs.
///
/// Biometric unlock is driven from the Dart side via `local_auth`; these
/// functions expose the Keychain-level operations and SSH keepalive control
/// that the Rust layer owns.
///
/// SSH keepalive suspend/resume are stubs until the SessionManager is wired
/// up in v0.62.0 (Mobile Foundation SSH layer).
/// Returns true if the device has biometric hardware and enrolled credentials.
///
/// On non-mobile targets this always returns false. The definitive check is
/// performed in Dart via `local_auth.canCheckBiometrics` before calling
/// `biometric_unlock`; this function is a secondary signal for the Rust layer.
Future<bool> biometricAvailable() =>
    TermexBridge.instance.api.crateApiMobileAuthBiometricAvailable();

/// Attempt to unlock the Keychain store using the platform biometric.
///
/// Returns `Ok(())` when the biometric challenge succeeds and the protected
/// Keychain entry is accessible.  Returns `Err(_)` on failure or cancellation.
///
/// The actual LAContext / BiometricPrompt challenge is orchestrated from Dart
/// (`local_auth`). This function is called *after* Dart confirms the
/// challenge was approved, to release the protected entry from Rust.
Future<void> biometricUnlock() =>
    TermexBridge.instance.api.crateApiMobileAuthBiometricUnlock();

/// Reduce keepalive frequency when the app enters the background.
///
/// Stub for v0.57.0 — real implementation in v0.62.0 once SessionManager
/// supports per-session keepalive interval adjustment.
Future<void> suspendAllKeepalives() =>
    TermexBridge.instance.api.crateApiMobileAuthSuspendAllKeepalives();

/// Restore full keepalive frequency when the app returns to the foreground.
Future<void> resumeAllKeepalives() =>
    TermexBridge.instance.api.crateApiMobileAuthResumeAllKeepalives();

/// Check whether an SSH session is still alive (channel responds to ping).
///
/// Returns `Ok(true)` if the session exists in the registry (channel is open),
/// `Ok(false)` if the session id is unknown (connection was dropped or never
/// established).
Future<bool> checkSessionAlive({required String sessionId}) =>
    TermexBridge.instance.api
        .crateApiMobileAuthCheckSessionAlive(sessionId: sessionId);

/// Attempt to reconnect a dropped SSH session.
///
/// Stub for v0.57.0 — full reconnect logic (re-auth, channel restore) is
/// implemented in v0.62.0.  For now the function signals "reconnect scheduled"
/// by returning Ok(()), letting the Dart reconnect banner dismiss itself.
Future<void> reconnectSession({required String sessionId}) =>
    TermexBridge.instance.api
        .crateApiMobileAuthReconnectSession(sessionId: sessionId);
