// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `signal_number`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CpuMetrics`, `DiskMetrics`, `MemoryMetrics`, `NetInterface`, `NetworkMetrics`, `SystemMetrics`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Validates a signal send request.  Returns `Ok(())` when safe to proceed.
///
/// `expert_mode` relaxes the protected-process whitelist (but PIDs 0/1 are
/// still blocked unconditionally).
Future<void> monitorValidateSignal(
        {required String signal,
        required int pid,
        required String processName,
        required bool expertMode}) =>
    TermexBridge.instance.api.crateApiMonitorMonitorValidateSignal(
        signal: signal,
        pid: pid,
        processName: processName,
        expertMode: expertMode);

Future<SystemStats> monitorGetStats({required String sessionId}) =>
    TermexBridge.instance.api
        .crateApiMonitorMonitorGetStats(sessionId: sessionId);

Future<List<ProcessInfo>> monitorListProcesses(
        {required String sessionId, required int limit}) =>
    TermexBridge.instance.api.crateApiMonitorMonitorListProcesses(
        sessionId: sessionId, limit: limit);

/// Sends a Unix signal to a remote process.  Front-end callers must supply
/// the `process_name` (captured from the process list) so this function can
/// enforce the protected-process whitelist.
Future<void> monitorSendSignal(
        {required String sessionId,
        required int pid,
        required String signal,
        required String processName,
        required bool expertMode}) =>
    TermexBridge.instance.api.crateApiMonitorMonitorSendSignal(
        sessionId: sessionId,
        pid: pid,
        signal: signal,
        processName: processName,
        expertMode: expertMode);

/// Legacy entrypoint without process-name validation — kept so older Dart
/// tests remain green.  Only accepts the 4 signals from v0.46.
Future<void> monitorSendSignalLegacy(
        {required String sessionId,
        required int pid,
        required String signal}) =>
    TermexBridge.instance.api.crateApiMonitorMonitorSendSignalLegacy(
        sessionId: sessionId, pid: pid, signal: signal);

Future<void> monitorStartPolling(
        {required String sessionId, required int intervalMs}) =>
    TermexBridge.instance.api.crateApiMonitorMonitorStartPolling(
        sessionId: sessionId, intervalMs: intervalMs);

Future<void> monitorStopPolling({required String sessionId}) =>
    TermexBridge.instance.api
        .crateApiMonitorMonitorStopPolling(sessionId: sessionId);

Future<List<String>> monitorActivePollingSessions() =>
    TermexBridge.instance.api.crateApiMonitorMonitorActivePollingSessions();

/// For tests: checks whether polling is currently active for `session_id`.
Future<bool> testIsPolling({required String sessionId}) =>
    TermexBridge.instance.api
        .crateApiMonitorTestIsPolling(sessionId: sessionId);

/// For tests: clears the polling registry.
Future<void> testClearPolling() =>
    TermexBridge.instance.api.crateApiMonitorTestClearPolling();

class ProcessInfo {
  final int pid;
  final String user;
  final double cpuPercent;
  final double memoryPercent;
  final String command;
  final String? startedAt;

  const ProcessInfo({
    required this.pid,
    required this.user,
    required this.cpuPercent,
    required this.memoryPercent,
    required this.command,
    this.startedAt,
  });

  @override
  int get hashCode =>
      pid.hashCode ^
      user.hashCode ^
      cpuPercent.hashCode ^
      memoryPercent.hashCode ^
      command.hashCode ^
      startedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessInfo &&
          runtimeType == other.runtimeType &&
          pid == other.pid &&
          user == other.user &&
          cpuPercent == other.cpuPercent &&
          memoryPercent == other.memoryPercent &&
          command == other.command &&
          startedAt == other.startedAt;
}

/// Legacy simpler DTO — kept for backwards compatibility with v0.46 Dart tests.
class SystemStats {
  final double cpuPercent;
  final BigInt memUsedMb;
  final BigInt memTotalMb;
  final double diskUsedGb;
  final double diskTotalGb;
  final BigInt netRxBytes;
  final BigInt netTxBytes;
  final String timestamp;

  const SystemStats({
    required this.cpuPercent,
    required this.memUsedMb,
    required this.memTotalMb,
    required this.diskUsedGb,
    required this.diskTotalGb,
    required this.netRxBytes,
    required this.netTxBytes,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      cpuPercent.hashCode ^
      memUsedMb.hashCode ^
      memTotalMb.hashCode ^
      diskUsedGb.hashCode ^
      diskTotalGb.hashCode ^
      netRxBytes.hashCode ^
      netTxBytes.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemStats &&
          runtimeType == other.runtimeType &&
          cpuPercent == other.cpuPercent &&
          memUsedMb == other.memUsedMb &&
          memTotalMb == other.memTotalMb &&
          diskUsedGb == other.diskUsedGb &&
          diskTotalGb == other.diskTotalGb &&
          netRxBytes == other.netRxBytes &&
          netTxBytes == other.netTxBytes &&
          timestamp == other.timestamp;
}
