// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'port_forward.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `as_str`, `from_str`

/// Returns `Some(port)` if `(bind_ip, port)` is already used by another rule
/// in either the persisted DB table or the runtime registry.
///
/// `exclude_id` takes `Option<String>` for Dart-compatibility (FRB cannot
/// auto-opaque an `Option<&str>`); all internal callers pass owned or cloned
/// strings anyway so the allocation cost is negligible.
Future<String?> portForwardFindConflict(
        {required String bindIp, required int localPort, String? excludeId}) =>
    TermexBridge.instance.api.crateApiPortForwardPortForwardFindConflict(
        bindIp: bindIp, localPort: localPort, excludeId: excludeId);

/// Scans `start..start+window` for a free port that does not conflict.
/// Returns the first free port or `None`.
Future<int?> portForwardSuggestFreePort(
        {required String bindIp, required int start, required int window}) =>
    TermexBridge.instance.api.crateApiPortForwardPortForwardSuggestFreePort(
        bindIp: bindIp, start: start, window: window);

/// Creates + starts a new forwarding rule.  Returns the rule ID.
///
/// - Rejects reserved/already-bound `(bind_ip, local_port)` pairs.
/// - Rejects `0.0.0.0` bind unless `allow_lan = true`.
Future<String> portForwardStart(
        {required String sessionId,
        required ForwardType forwardType,
        required int localPort,
        required String remoteHost,
        required int remotePort}) =>
    TermexBridge.instance.api.crateApiPortForwardPortForwardStart(
        sessionId: sessionId,
        forwardType: forwardType,
        localPort: localPort,
        remoteHost: remoteHost,
        remotePort: remotePort);

Future<String> portForwardStartEx(
        {required String sessionId,
        required ForwardType forwardType,
        required String bindIp,
        required int localPort,
        required String remoteHost,
        required int remotePort,
        required bool autoStart,
        required bool allowLan}) =>
    TermexBridge.instance.api.crateApiPortForwardPortForwardStartEx(
        sessionId: sessionId,
        forwardType: forwardType,
        bindIp: bindIp,
        localPort: localPort,
        remoteHost: remoteHost,
        remotePort: remotePort,
        autoStart: autoStart,
        allowLan: allowLan);

/// Stops and removes a port-forwarding rule by `rule_id`.
Future<void> portForwardStop({required String ruleId}) =>
    TermexBridge.instance.api
        .crateApiPortForwardPortForwardStop(ruleId: ruleId);

/// Pauses a rule (mark inactive) without deleting.
Future<void> portForwardDisable({required String ruleId}) =>
    TermexBridge.instance.api
        .crateApiPortForwardPortForwardDisable(ruleId: ruleId);

/// Lists active port-forwarding rules for a specific `session_id`.
Future<List<ForwardRule>> portForwardList({required String sessionId}) =>
    TermexBridge.instance.api
        .crateApiPortForwardPortForwardList(sessionId: sessionId);

/// Lists all active port-forwarding rules across all sessions.
Future<List<ForwardRule>> portForwardListAll() =>
    TermexBridge.instance.api.crateApiPortForwardPortForwardListAll();

/// Returns the status of `rule_id`, or `ForwardStatus::Stopped` if unknown.
Future<ForwardStatus> portForwardStatus({required String ruleId}) =>
    TermexBridge.instance.api
        .crateApiPortForwardPortForwardStatus(ruleId: ruleId);

/// For tests: clears the forwarding registry.
Future<void> testClearRegistry() =>
    TermexBridge.instance.api.crateApiPortForwardTestClearRegistry();

class ForwardRule {
  final String id;
  final String sessionId;
  final ForwardType forwardType;
  final String bindIp;
  final int localPort;
  final String remoteHost;
  final int remotePort;
  final bool isActive;
  final bool autoStart;

  const ForwardRule({
    required this.id,
    required this.sessionId,
    required this.forwardType,
    required this.bindIp,
    required this.localPort,
    required this.remoteHost,
    required this.remotePort,
    required this.isActive,
    required this.autoStart,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      forwardType.hashCode ^
      bindIp.hashCode ^
      localPort.hashCode ^
      remoteHost.hashCode ^
      remotePort.hashCode ^
      isActive.hashCode ^
      autoStart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForwardRule &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          forwardType == other.forwardType &&
          bindIp == other.bindIp &&
          localPort == other.localPort &&
          remoteHost == other.remoteHost &&
          remotePort == other.remotePort &&
          isActive == other.isActive &&
          autoStart == other.autoStart;
}

@freezed
sealed class ForwardStatus with _$ForwardStatus {
  const ForwardStatus._();

  const factory ForwardStatus.stopped() = ForwardStatus_Stopped;
  const factory ForwardStatus.running() = ForwardStatus_Running;
  const factory ForwardStatus.portConflict(
    String field0,
  ) = ForwardStatus_PortConflict;
  const factory ForwardStatus.error(
    String field0,
  ) = ForwardStatus_Error;
}

enum ForwardType {
  local,
  remote,
  dynamic_,
  ;
}
