// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `as_str`, `from_str`

Future<List<ProxyConfig>> proxyList() =>
    TermexBridge.instance.api.crateApiProxyProxyList();

/// Creates a new proxy configuration.  If `password` is `Some`, the caller is
/// responsible for also persisting it to the OS keychain at
/// `proxy:{id}:password` — the FRB layer intentionally does not store plain
/// passwords anywhere.
Future<ProxyConfig> proxyCreate(
        {required ProxyType proxyType,
        required String host,
        required int port,
        String? username}) =>
    TermexBridge.instance.api.crateApiProxyProxyCreate(
        proxyType: proxyType, host: host, port: port, username: username);

Future<ProxyConfig> proxyCreateEx(
        {required String name,
        required ProxyType proxyType,
        required String host,
        required int port,
        String? username,
        required bool tlsEnabled}) =>
    TermexBridge.instance.api.crateApiProxyProxyCreateEx(
        name: name,
        proxyType: proxyType,
        host: host,
        port: port,
        username: username,
        tlsEnabled: tlsEnabled);

Future<void> proxyDelete({required String id}) =>
    TermexBridge.instance.api.crateApiProxyProxyDelete(id: id);

Future<void> proxySetDefault({required String id}) =>
    TermexBridge.instance.api.crateApiProxyProxySetDefault(id: id);

Future<ProxyConfig?> proxyGetDefault() =>
    TermexBridge.instance.api.crateApiProxyProxyGetDefault();

Future<bool> proxyTestConnection({required String id}) =>
    TermexBridge.instance.api.crateApiProxyProxyTestConnection(id: id);

/// Returns the canonical keychain key used to store `proxy_id`'s password.
Future<String> proxyKeychainKey({required String proxyId}) =>
    TermexBridge.instance.api.crateApiProxyProxyKeychainKey(proxyId: proxyId);

/// Updates (or inserts) a cached health latency for `proxy_id`.  Called by
/// the background health-check job.
Future<void> proxyRecordHealth({required String proxyId, int? latencyMs}) =>
    TermexBridge.instance.api
        .crateApiProxyProxyRecordHealth(proxyId: proxyId, latencyMs: latencyMs);

Future<int> torStart() => TermexBridge.instance.api.crateApiProxyTorStart();

Future<void> torStop() => TermexBridge.instance.api.crateApiProxyTorStop();

Future<TorStatus> torStatus() =>
    TermexBridge.instance.api.crateApiProxyTorStatus();

/// For tests: clears the proxy registry and tor state.
Future<void> testClearRegistry() =>
    TermexBridge.instance.api.crateApiProxyTestClearRegistry();

class ProxyConfig {
  final String id;
  final ProxyType proxyType;
  final String host;
  final int port;
  final String? username;
  final bool isDefault;
  final bool tlsEnabled;
  final int? healthMs;
  final String name;

  const ProxyConfig({
    required this.id,
    required this.proxyType,
    required this.host,
    required this.port,
    this.username,
    required this.isDefault,
    required this.tlsEnabled,
    this.healthMs,
    required this.name,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      proxyType.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      isDefault.hashCode ^
      tlsEnabled.hashCode ^
      healthMs.hashCode ^
      name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          proxyType == other.proxyType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          isDefault == other.isDefault &&
          tlsEnabled == other.tlsEnabled &&
          healthMs == other.healthMs &&
          name == other.name;
}

enum ProxyType {
  socks5,
  http,
  tor,
  ;
}

class TorStatus {
  final bool running;
  final int bootstrapPercent;
  final int? socksPort;
  final int circuitsCount;
  final String? lastError;

  const TorStatus({
    required this.running,
    required this.bootstrapPercent,
    this.socksPort,
    required this.circuitsCount,
    this.lastError,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      bootstrapPercent.hashCode ^
      socksPort.hashCode ^
      circuitsCount.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorStatus &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          bootstrapPercent == other.bootstrapPercent &&
          socksPort == other.socksPort &&
          circuitsCount == other.circuitsCount &&
          lastError == other.lastError;
}
