// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `random_hex6`, `sanitize_server_name`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AsciicastHeader`, `CastEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Renders the canonical `.cast` filename for a new recording.
Future<String> recordingRenderFilename({required String serverName}) =>
    TermexBridge.instance.api
        .crateApiRecordingRecordingRenderFilename(serverName: serverName);

/// Renders the filename for an auto-split part (part2+).
Future<String> recordingRenderPartFilename(
        {required String basename, required int partN}) =>
    TermexBridge.instance.api.crateApiRecordingRecordingRenderPartFilename(
        basename: basename, partN: partN);

/// Begins recording terminal output for `session_id`.  Returns a new recording id.
Future<String> recordingStart({required String sessionId, String? title}) =>
    TermexBridge.instance.api
        .crateApiRecordingRecordingStart(sessionId: sessionId, title: title);

/// Stops an active recording and returns its metadata.
Future<RecordingEntry> recordingStop({required String recordingId}) =>
    TermexBridge.instance.api
        .crateApiRecordingRecordingStop(recordingId: recordingId);

/// Lists all known recordings (legacy DTO).
Future<List<RecordingEntry>> recordingList() =>
    TermexBridge.instance.api.crateApiRecordingRecordingList();

/// Lists recordings with the full v0.47 DTO shape.
Future<List<RecordingDto>> recordingListFull() =>
    TermexBridge.instance.api.crateApiRecordingRecordingListFull();

/// Registers a follow-up part (part2+) linked to `parent_id`.
Future<String> recordingRegisterPart(
        {required String parentId,
        required String sessionId,
        required String filePath}) =>
    TermexBridge.instance.api.crateApiRecordingRecordingRegisterPart(
        parentId: parentId, sessionId: sessionId, filePath: filePath);

/// Deletes a recording by `id` (cascade to parts is NOT applied — call the
/// helper below to delete a full group).
Future<void> recordingDelete({required String id}) =>
    TermexBridge.instance.api.crateApiRecordingRecordingDelete(id: id);

/// Deletes a recording and every follow-up part linked to it.
Future<int> recordingDeleteGroup({required String parentId}) =>
    TermexBridge.instance.api
        .crateApiRecordingRecordingDeleteGroup(parentId: parentId);

/// Returns the filesystem path for a recording's `.cast` file.
Future<String> recordingGetPath({required String id}) =>
    TermexBridge.instance.api.crateApiRecordingRecordingGetPath(id: id);

/// Exports a recording to `dest_path`.  Copies the underlying `.cast` file.
Future<void> recordingExport({required String id, required String destPath}) =>
    TermexBridge.instance.api
        .crateApiRecordingRecordingExport(id: id, destPath: destPath);

/// Marks `id` as encrypted (after caller has re-encrypted the underlying file).
Future<void> recordingMarkEncrypted({required String id}) =>
    TermexBridge.instance.api.crateApiRecordingRecordingMarkEncrypted(id: id);

/// Deletes recordings older than `days` days.  Returns count deleted.
Future<int> recordingCleanupExpired({required int days}) =>
    TermexBridge.instance.api
        .crateApiRecordingRecordingCleanupExpired(days: days);

/// For tests: clears the in-memory recording registry.
Future<void> testClearRegistry() =>
    TermexBridge.instance.api.crateApiRecordingTestClearRegistry();

/// Full recording metadata (v0.47 spec §9.5.2).
class RecordingDto {
  final String id;
  final String sessionId;
  final String serverId;
  final String serverName;
  final String filePath;
  final BigInt fileSize;
  final BigInt durationMs;
  final int cols;
  final int rows;
  final int eventCount;
  final String? summary;
  final bool autoRecorded;
  final String startedAt;
  final String? endedAt;
  final String? parentId;
  final bool isEncrypted;

  const RecordingDto({
    required this.id,
    required this.sessionId,
    required this.serverId,
    required this.serverName,
    required this.filePath,
    required this.fileSize,
    required this.durationMs,
    required this.cols,
    required this.rows,
    required this.eventCount,
    this.summary,
    required this.autoRecorded,
    required this.startedAt,
    this.endedAt,
    this.parentId,
    required this.isEncrypted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      serverId.hashCode ^
      serverName.hashCode ^
      filePath.hashCode ^
      fileSize.hashCode ^
      durationMs.hashCode ^
      cols.hashCode ^
      rows.hashCode ^
      eventCount.hashCode ^
      summary.hashCode ^
      autoRecorded.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode ^
      parentId.hashCode ^
      isEncrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordingDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          serverId == other.serverId &&
          serverName == other.serverName &&
          filePath == other.filePath &&
          fileSize == other.fileSize &&
          durationMs == other.durationMs &&
          cols == other.cols &&
          rows == other.rows &&
          eventCount == other.eventCount &&
          summary == other.summary &&
          autoRecorded == other.autoRecorded &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt &&
          parentId == other.parentId &&
          isEncrypted == other.isEncrypted;
}

/// Legacy simpler DTO for v0.46-era Dart tests.
class RecordingEntry {
  final String id;
  final String sessionId;
  final String? title;
  final String filePath;
  final BigInt durationSeconds;
  final BigInt sizeBytes;
  final String createdAt;

  const RecordingEntry({
    required this.id,
    required this.sessionId,
    this.title,
    required this.filePath,
    required this.durationSeconds,
    required this.sizeBytes,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      title.hashCode ^
      filePath.hashCode ^
      durationSeconds.hashCode ^
      sizeBytes.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordingEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          title == other.title &&
          filePath == other.filePath &&
          durationSeconds == other.durationSeconds &&
          sizeBytes == other.sizeBytes &&
          createdAt == other.createdAt;
}
