// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `sql_box`, `write_helper`

/// Get the current snapshot — `None` when no metrics row exists
/// for this task yet (caller defaults to TaskMetrics::empty).
Future<TaskMetrics?> reliabilityGet({required String taskId}) =>
    TermexBridge.instance.api.crateApiReliabilityReliabilityGet(taskId: taskId);

Future<void> reliabilitySave({required TaskMetrics m}) =>
    TermexBridge.instance.api.crateApiReliabilityReliabilitySave(m: m);

Future<void> reliabilityDelete({required String taskId}) =>
    TermexBridge.instance.api
        .crateApiReliabilityReliabilityDelete(taskId: taskId);

Future<List<TaskMetrics>> reliabilityList() =>
    TermexBridge.instance.api.crateApiReliabilityReliabilityList();

Future<void> reliabilityRecordReconnect(
        {required String taskId, required String nowRfc3339}) =>
    TermexBridge.instance.api.crateApiReliabilityReliabilityRecordReconnect(
        taskId: taskId, nowRfc3339: nowRfc3339);

/// Batch reconnect — called by the app-level orchestrator after a
/// successful WS reconnect with the list of task ids the user was
/// subscribed to. Returns the number of rows bumped.
Future<int> reliabilityRecordReconnectBatch(
        {required List<String> taskIds, required String nowRfc3339}) =>
    TermexBridge.instance.api
        .crateApiReliabilityReliabilityRecordReconnectBatch(
            taskIds: taskIds, nowRfc3339: nowRfc3339);

Future<void> reliabilityRecordWsSession(
        {required String taskId,
        required BigInt durationMs,
        required String nowRfc3339}) =>
    TermexBridge.instance.api.crateApiReliabilityReliabilityRecordWsSession(
        taskId: taskId, durationMs: durationMs, nowRfc3339: nowRfc3339);

Future<void> reliabilityRecordBgDuration(
        {required String taskId,
        required BigInt durationMs,
        required String nowRfc3339}) =>
    TermexBridge.instance.api.crateApiReliabilityReliabilityRecordBgDuration(
        taskId: taskId, durationMs: durationMs, nowRfc3339: nowRfc3339);

Future<void> reliabilityRecordPushLatency(
        {required String taskId,
        required int latencyMs,
        required String nowRfc3339}) =>
    TermexBridge.instance.api.crateApiReliabilityReliabilityRecordPushLatency(
        taskId: taskId, latencyMs: latencyMs, nowRfc3339: nowRfc3339);

Future<void> reliabilityRecordHandoff(
        {required String taskId, required String nowRfc3339}) =>
    TermexBridge.instance.api.crateApiReliabilityReliabilityRecordHandoff(
        taskId: taskId, nowRfc3339: nowRfc3339);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TaskMetrics>>
abstract class TaskMetrics implements RustOpaqueInterface {}
