// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_str`, `from_core`, `from_str`, `row_to_dto`, `to_core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// List all servers ordered by sort_order then name.
Future<List<ServerDto>> listServers() =>
    TermexBridge.instance.api.crateApiServerListServers();

/// Retrieve a single server by ID.
Future<ServerDto?> getServer({required String id}) =>
    TermexBridge.instance.api.crateApiServerGetServer(id: id);

/// Create a new server entry, storing password in keychain if provided.
Future<ServerDto> createServer({required ServerInput input}) =>
    TermexBridge.instance.api.crateApiServerCreateServer(input: input);

/// Update an existing server, refreshing keychain entry for password.
Future<ServerDto> updateServer(
        {required String id, required ServerInput input}) =>
    TermexBridge.instance.api.crateApiServerUpdateServer(id: id, input: input);

/// Delete a server by ID.
Future<void> deleteServer({required String id}) =>
    TermexBridge.instance.api.crateApiServerDeleteServer(id: id);

/// Move a server to a different group (or un-group it).
Future<void> moveServerToGroup({required String id, String? groupId}) =>
    TermexBridge.instance.api
        .crateApiServerMoveServerToGroup(id: id, groupId: groupId);

/// Update the last_connected timestamp for a server to now.
Future<void> updateLastConnected({required String id}) =>
    TermexBridge.instance.api.crateApiServerUpdateLastConnected(id: id);

/// List quick connect history, newest first, capped at 20 entries.
Future<List<QuickConnectEntry>> listQuickConnectHistory() =>
    TermexBridge.instance.api.crateApiServerListQuickConnectHistory();

/// Add an entry to quick connect history and prune entries beyond the most recent 20.
Future<void> addQuickConnectHistory(
        {required String host, required int port, required String username}) =>
    TermexBridge.instance.api.crateApiServerAddQuickConnectHistory(
        host: host, port: port, username: username);

/// Clear all quick connect history.
Future<void> clearQuickConnectHistory() =>
    TermexBridge.instance.api.crateApiServerClearQuickConnectHistory();

/// Auth type exposed to Flutter — superset of core AuthType.
enum AuthType {
  password,
  key,
  agent,
  interactive,
  ;
}

/// Quick connect history entry.
class QuickConnectEntry {
  final String id;
  final String host;
  final int port;
  final String username;
  final String usedAt;

  const QuickConnectEntry({
    required this.id,
    required this.host,
    required this.port,
    required this.username,
    required this.usedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      usedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuickConnectEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          usedAt == other.usedAt;
}

/// Lightweight server DTO for Flutter.
class ServerDto {
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final AuthType authType;
  final String? keyPath;
  final String? groupId;
  final int sortOrder;
  final List<String> tags;
  final String? lastConnected;
  final String createdAt;
  final String updatedAt;

  const ServerDto({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    required this.authType,
    this.keyPath,
    this.groupId,
    required this.sortOrder,
    required this.tags,
    this.lastConnected,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      authType.hashCode ^
      keyPath.hashCode ^
      groupId.hashCode ^
      sortOrder.hashCode ^
      tags.hashCode ^
      lastConnected.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          authType == other.authType &&
          keyPath == other.keyPath &&
          groupId == other.groupId &&
          sortOrder == other.sortOrder &&
          tags == other.tags &&
          lastConnected == other.lastConnected &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Input for creating or editing a server.
class ServerInput {
  final String name;
  final String host;
  final int port;
  final String username;
  final AuthType authType;
  final String? password;
  final String? keyPath;
  final String? groupId;
  final List<String> tags;

  const ServerInput({
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    required this.authType,
    this.password,
    this.keyPath,
    this.groupId,
    required this.tags,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      authType.hashCode ^
      password.hashCode ^
      keyPath.hashCode ^
      groupId.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          authType == other.authType &&
          password == other.password &&
          keyPath == other.keyPath &&
          groupId == other.groupId &&
          tags == other.tags;
}
