// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `csv_escape`, `map_to_settings`, `settings_to_pairs`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Loads settings from the database.  Any key missing from the table falls
/// back to its built-in default.  When the database is not unlocked the
/// built-in defaults are returned.
Future<AppSettings> settingsLoad() =>
    TermexBridge.instance.api.crateApiSettingsSettingsLoad();

/// Persists `settings` to the `settings` KV table.  No-op when the database
/// is not unlocked.
Future<void> settingsSave({required AppSettings settings}) =>
    TermexBridge.instance.api.crateApiSettingsSettingsSave(settings: settings);

/// Exports the full settings bundle to a password-protected `.termex` file.
///
/// When `password` is empty the payload is written as plain JSON with
/// `schema_version: 2`; otherwise it is wrapped in the AES-256-GCM +
/// Argon2id binary container described in §4.8.5 of the v0.46 spec.
Future<void> settingsExport({required String path, required String password}) =>
    TermexBridge.instance.api
        .crateApiSettingsSettingsExport(path: path, password: password);

/// Imports settings from an export file.  Handles both plain-JSON and
/// encrypted `.termex` files (magic-number sniffing).
Future<AppSettings> settingsImport(
        {required String path, required String password}) =>
    TermexBridge.instance.api
        .crateApiSettingsSettingsImport(path: path, password: password);

/// Resets every setting to its built-in default value by clearing overrides
/// from the `settings` KV table.
Future<void> settingsResetToDefaults() =>
    TermexBridge.instance.api.crateApiSettingsSettingsResetToDefaults();

/// Deletes all rows from the `quick_connect_history` table.
Future<void> privacyClearConnectionHistory() =>
    TermexBridge.instance.api.crateApiSettingsPrivacyClearConnectionHistory();

/// Deletes all AI conversation records (cascades to `ai_messages`).
Future<void> privacyClearAiConversations() =>
    TermexBridge.instance.api.crateApiSettingsPrivacyClearAiConversations();

/// Resets snippet usage statistics (use counts and last-used timestamps).
Future<void> privacyClearSnippetStats() =>
    TermexBridge.instance.api.crateApiSettingsPrivacyClearSnippetStats();

/// Permanently erases **all** user data after verifying the confirmation
/// string matches `"DELETE ALL"`.  `master_password` is accepted but not yet
/// verified (master-password store lives in the keychain module which is
/// desktop-only).
///
/// Returns `Err("Confirmation text mismatch")` if the confirmation is wrong.
Future<void> privacyGdprEraseAll(
        {required String masterPassword, required String confirmation}) =>
    TermexBridge.instance.api.crateApiSettingsPrivacyGdprEraseAll(
        masterPassword: masterPassword, confirmation: confirmation);

/// Returns up to `limit` audit-log entries, optionally filtered by
/// `event_type`.  Results are ordered newest-first.
Future<List<AuditLogEntry>> auditList(
        {required int limit, String? eventType}) =>
    TermexBridge.instance.api
        .crateApiSettingsAuditList(limit: limit, eventType: eventType);

/// Appends one audit log entry.  Detail is stored verbatim — callers are
/// responsible for redaction before invoking this function (§12.8 of spec).
Future<void> auditAppend({required String eventType, required String detail}) =>
    TermexBridge.instance.api
        .crateApiSettingsAuditAppend(eventType: eventType, detail: detail);

/// Exports audit-log entries from the last `days` days (or all if `None`) to a
/// CSV file at `path`.  Format: UTF-8 with BOM, headers
/// `timestamp,event_type,detail`.  Empty database writes only the header row.
Future<void> auditExportCsv({required String path, int? days}) =>
    TermexBridge.instance.api
        .crateApiSettingsAuditExportCsv(path: path, days: days);

/// Snapshot of every user-configurable setting.
class AppSettings {
  /// Theme mode: `"dark"` | `"light"` | `"system"`.
  final String themeMode;

  /// Terminal colour-scheme name (e.g. `"One Dark"`).
  final String colorScheme;

  /// Terminal font family.
  final String fontFamily;

  /// Terminal font size in points.
  final double fontSize;

  /// Cursor shape: `"block"` | `"underline"` | `"bar"`.
  final String cursorShape;

  /// Whether the cursor blinks.
  final bool cursorBlink;

  /// Number of lines to keep in the scrollback buffer.
  final int scrollbackLines;

  /// Tab-stop width: `2` | `4` | `8`.
  final int tabWidth;

  /// UI language: `"zh-CN"` | `"en-US"`.
  final String language;

  /// Automatically run AI diagnostics on command failure.
  final bool aiAutoDiagnose;

  /// Number of terminal lines to include in AI context.
  final int aiContextLines;

  /// Automated backup frequency: `"off"` | `"daily"` | `"weekly"`.
  final String backupFrequency;

  /// Audit-log retention: `30` | `90` | `365` | `-1` (永久 / forever).
  final int auditRetentionDays;

  /// TCP port for the local AI model server.
  final int localAiPort;

  /// CPU-thread count for local AI inference.
  final int localAiThreads;

  /// Context-window size (tokens) for local AI.
  final int localAiContextSize;

  /// Path to kubeconfig file used by cloud K8s integration (§13.5 of v0.46 spec).
  final String k8SKubeconfigPath;

  const AppSettings({
    required this.themeMode,
    required this.colorScheme,
    required this.fontFamily,
    required this.fontSize,
    required this.cursorShape,
    required this.cursorBlink,
    required this.scrollbackLines,
    required this.tabWidth,
    required this.language,
    required this.aiAutoDiagnose,
    required this.aiContextLines,
    required this.backupFrequency,
    required this.auditRetentionDays,
    required this.localAiPort,
    required this.localAiThreads,
    required this.localAiContextSize,
    required this.k8SKubeconfigPath,
  });

  static Future<AppSettings> default_() =>
      TermexBridge.instance.api.crateApiSettingsAppSettingsDefault();

  @override
  int get hashCode =>
      themeMode.hashCode ^
      colorScheme.hashCode ^
      fontFamily.hashCode ^
      fontSize.hashCode ^
      cursorShape.hashCode ^
      cursorBlink.hashCode ^
      scrollbackLines.hashCode ^
      tabWidth.hashCode ^
      language.hashCode ^
      aiAutoDiagnose.hashCode ^
      aiContextLines.hashCode ^
      backupFrequency.hashCode ^
      auditRetentionDays.hashCode ^
      localAiPort.hashCode ^
      localAiThreads.hashCode ^
      localAiContextSize.hashCode ^
      k8SKubeconfigPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          themeMode == other.themeMode &&
          colorScheme == other.colorScheme &&
          fontFamily == other.fontFamily &&
          fontSize == other.fontSize &&
          cursorShape == other.cursorShape &&
          cursorBlink == other.cursorBlink &&
          scrollbackLines == other.scrollbackLines &&
          tabWidth == other.tabWidth &&
          language == other.language &&
          aiAutoDiagnose == other.aiAutoDiagnose &&
          aiContextLines == other.aiContextLines &&
          backupFrequency == other.backupFrequency &&
          auditRetentionDays == other.auditRetentionDays &&
          localAiPort == other.localAiPort &&
          localAiThreads == other.localAiThreads &&
          localAiContextSize == other.localAiContextSize &&
          k8SKubeconfigPath == other.k8SKubeconfigPath;
}

/// A single entry in the audit log.
class AuditLogEntry {
  final String id;
  final String eventType;
  final String detail;
  final String createdAt;

  const AuditLogEntry({
    required this.id,
    required this.eventType,
    required this.detail,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ eventType.hashCode ^ detail.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditLogEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          eventType == other.eventType &&
          detail == other.detail &&
          createdAt == other.createdAt;
}
