// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../frb_sftp_emitter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `permissions_to_mode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Opens (or reuses) an SFTP channel on an existing SSH session.
/// Returns the canonical remote working directory.
Future<String> openSftpChannel({required String sessionId}) =>
    TermexBridge.instance.api.crateApiSftpOpenSftpChannel(sessionId: sessionId);

/// Closes the SFTP channel for `session_id`.
Future<void> closeSftpChannel({required String sessionId}) =>
    TermexBridge.instance.api
        .crateApiSftpCloseSftpChannel(sessionId: sessionId);

/// Returns `true` if an SFTP channel is currently cached for `session_id`.
Future<bool> isSftpOpen({required String sessionId}) =>
    TermexBridge.instance.api.crateApiSftpIsSftpOpen(sessionId: sessionId);

/// Lists the contents of `path` on the remote, sorted dirs-first.
Future<List<SftpFileDto>> sftpList(
        {required String sessionId, required String path}) =>
    TermexBridge.instance.api
        .crateApiSftpSftpList(sessionId: sessionId, path: path);

/// Creates a remote directory.
Future<void> sftpMkdir({required String sessionId, required String path}) =>
    TermexBridge.instance.api
        .crateApiSftpSftpMkdir(sessionId: sessionId, path: path);

/// Deletes a remote file.
Future<void> sftpRemove({required String sessionId, required String path}) =>
    TermexBridge.instance.api
        .crateApiSftpSftpRemove(sessionId: sessionId, path: path);

/// Deletes a remote directory. Non-recursive — the UI must walk children
/// and delete them first. A recursive variant will land in v0.51.
Future<void> sftpRmdir({required String sessionId, required String path}) =>
    TermexBridge.instance.api
        .crateApiSftpSftpRmdir(sessionId: sessionId, path: path);

/// Renames (moves) a remote path.
Future<void> sftpRename(
        {required String sessionId,
        required String from,
        required String to}) =>
    TermexBridge.instance.api
        .crateApiSftpSftpRename(sessionId: sessionId, from: from, to: to);

/// Changes the Unix permission bits of a remote file.
///
/// Currently unsupported — russh-sftp 2.1 does not expose `setstat`. Returns
/// an explicit error so the Flutter UI can surface the limitation. See
/// `docs/tech-debt.md` once russh-sftp ships the API.
Future<void> sftpChmod(
        {required String sessionId, required String path, required int mode}) =>
    TermexBridge.instance.api
        .crateApiSftpSftpChmod(sessionId: sessionId, path: path, mode: mode);

/// Canonicalises a remote path (resolves `~`, symlinks, `..`).
Future<String> sftpCanonicalize(
        {required String sessionId, required String path}) =>
    TermexBridge.instance.api
        .crateApiSftpSftpCanonicalize(sessionId: sessionId, path: path);

/// Downloads a remote file to `local_path`. Returns immediately; progress
/// is delivered via [`poll_sftp_progress`].
Future<void> sftpDownload(
        {required String sessionId,
        required String remotePath,
        required String localPath,
        required String transferId}) =>
    TermexBridge.instance.api.crateApiSftpSftpDownload(
        sessionId: sessionId,
        remotePath: remotePath,
        localPath: localPath,
        transferId: transferId);

/// Uploads a local file to `remote_path`.
Future<void> sftpUpload(
        {required String sessionId,
        required String localPath,
        required String remotePath,
        required String transferId}) =>
    TermexBridge.instance.api.crateApiSftpSftpUpload(
        sessionId: sessionId,
        localPath: localPath,
        remotePath: remotePath,
        transferId: transferId);

/// Streams a file from one SFTP session to another (server-to-server copy).
Future<void> sftpTransferBetween(
        {required String srcSessionId,
        required String srcPath,
        required String dstSessionId,
        required String dstPath,
        required String transferId}) =>
    TermexBridge.instance.api.crateApiSftpSftpTransferBetween(
        srcSessionId: srcSessionId,
        srcPath: srcPath,
        dstSessionId: dstSessionId,
        dstPath: dstPath,
        transferId: transferId);

/// Polls the progress queue for a given transfer. Drains pending updates
/// and returns them in chronological order.
Future<List<SftpTransferProgress>> pollSftpProgress(
        {required String transferId}) =>
    TermexBridge.instance.api
        .crateApiSftpPollSftpProgress(transferId: transferId);

/// Cancels an in-flight transfer identified by `transfer_id`.
///
/// v0.50.x: no-op. russh-sftp reads/writes are not cancellable mid-chunk;
/// a proper implementation needs a CancellationToken plumbed through the
/// transfer loop. Tracked as a small follow-up.
Future<void> sftpCancelTransfer({required String transferId}) =>
    TermexBridge.instance.api
        .crateApiSftpSftpCancelTransfer(transferId: transferId);

/// Records a completed command in the `command_history` table.
Future<String> recordCommand(
        {required String sessionId,
        String? serverId,
        required String command,
        int? exitCode,
        required String startedAt,
        PlatformInt64? durationMs}) =>
    TermexBridge.instance.api.crateApiSftpRecordCommand(
        sessionId: sessionId,
        serverId: serverId,
        command: command,
        exitCode: exitCode,
        startedAt: startedAt,
        durationMs: durationMs);

/// Returns the most recent `limit` commands for `server_id`, newest first.
Future<List<CommandHistoryEntry>> listCommandHistory(
        {required String serverId, required int limit}) =>
    TermexBridge.instance.api
        .crateApiSftpListCommandHistory(serverId: serverId, limit: limit);

/// Clears all command history for `server_id`.
Future<void> clearCommandHistory({required String serverId}) =>
    TermexBridge.instance.api
        .crateApiSftpClearCommandHistory(serverId: serverId);

/// Returns the canonical home directory for tests that cannot open a real
/// SFTP subsystem. Matches the behaviour of the previous in-memory stub.
Future<void> testInsertSession({required String sessionId}) =>
    TermexBridge.instance.api
        .crateApiSftpTestInsertSession(sessionId: sessionId);

Future<void> testClearRegistry() =>
    TermexBridge.instance.api.crateApiSftpTestClearRegistry();

/// A record of a single shell command (OSC 133 tracking).
class CommandHistoryEntry {
  final String id;
  final String sessionId;
  final String? serverId;
  final String command;
  final int? exitCode;
  final String startedAt;
  final PlatformInt64? durationMs;

  const CommandHistoryEntry({
    required this.id,
    required this.sessionId,
    this.serverId,
    required this.command,
    this.exitCode,
    required this.startedAt,
    this.durationMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      serverId.hashCode ^
      command.hashCode ^
      exitCode.hashCode ^
      startedAt.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandHistoryEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          serverId == other.serverId &&
          command == other.command &&
          exitCode == other.exitCode &&
          startedAt == other.startedAt &&
          durationMs == other.durationMs;
}

/// A remote filesystem entry returned by [sftp_list].
class SftpFileDto {
  final String name;
  final String path;
  final bool isDir;
  final bool isSymlink;

  /// File size in bytes.
  final BigInt size;

  /// Unix permission bits (e.g. 0o644).
  final int permissions;

  /// Seconds since Unix epoch.
  final PlatformInt64 modifiedAt;

  /// Owner username, if available.
  final String? owner;

  const SftpFileDto({
    required this.name,
    required this.path,
    required this.isDir,
    required this.isSymlink,
    required this.size,
    required this.permissions,
    required this.modifiedAt,
    this.owner,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      isSymlink.hashCode ^
      size.hashCode ^
      permissions.hashCode ^
      modifiedAt.hashCode ^
      owner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpFileDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          isSymlink == other.isSymlink &&
          size == other.size &&
          permissions == other.permissions &&
          modifiedAt == other.modifiedAt &&
          owner == other.owner;
}
