// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_chain_emitter.dart';
import '../frb_generated.dart';
import '../frb_ssh_emitter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect_direct`, `load_connect_row`, `mark_last_connected`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectRow`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Opens an SSH session and starts streaming terminal events to a
/// per-session queue that Dart polls via `poll_ssh_events`.
///
/// Scope (v0.50.x): direct TCP connection + password or key auth against
/// the server's stored credentials. Chain-through-bastion and network
/// proxies remain routed through the legacy Tauri path; see
/// `docs/tech-debt.md` T-9 for the follow-up plan.
Future<String> openSshSession(
        {required String serverId, required int cols, required int rows}) =>
    TermexBridge.instance.api
        .crateApiSshOpenSshSession(serverId: serverId, cols: cols, rows: rows);

/// Drains pending events for a session. Called by the Dart polling task.
Future<List<SshStreamEvent>> pollSshEvents({required String sessionId}) =>
    TermexBridge.instance.api.crateApiSshPollSshEvents(sessionId: sessionId);

/// Sends raw bytes to the shell stdin. Handles both SSH and local PTY sessions.
Future<void> writeStdin({required String sessionId, required List<int> data}) =>
    TermexBridge.instance.api
        .crateApiSshWriteStdin(sessionId: sessionId, data: data);

/// Resizes the pseudo-terminal. Handles both SSH and local PTY sessions.
Future<void> resizeTerminal(
        {required String sessionId, required int cols, required int rows}) =>
    TermexBridge.instance.api.crateApiSshResizeTerminal(
        sessionId: sessionId, cols: cols, rows: rows);

/// Closes a session. Handles both SSH and local PTY sessions.
Future<void> closeSshSession({required String sessionId}) =>
    TermexBridge.instance.api.crateApiSshCloseSshSession(sessionId: sessionId);

/// Checks whether an SSH agent is available by inspecting `SSH_AUTH_SOCK`.
Future<bool> checkSshAgentAvailable() =>
    TermexBridge.instance.api.crateApiSshCheckSshAgentAvailable();

/// Runs a full TCP + SSH handshake + auth against a transient set of
/// connection params and disconnects. Returns `Ok(())` on success, or the
/// underlying error message. Nothing is written to DB or keychain — used by
/// the add/edit server dialog to verify credentials before persisting.
Future<void> testSshConnection({required SshConnectionTestParams params}) =>
    TermexBridge.instance.api.crateApiSshTestSshConnection(params: params);

/// Opens a new session to the same server as an existing session.
///
/// v0.50.x: re-resolves the server from its last-connected record. True
/// channel multiplexing over a shared russh handle is tracked in tech
/// debt T-9 and will land with the proxy-chain migration.
Future<String> openSshSessionClone(
        {required String existingSessionId,
        required int cols,
        required int rows}) =>
    TermexBridge.instance.api.crateApiSshOpenSshSessionClone(
        existingSessionId: existingSessionId, cols: cols, rows: rows);

/// Checks the host-key status for a connection by querying the `known_hosts` table.
///
/// Returns one of:
/// - `"trusted"` — fingerprint matches the stored record.
/// - `"new:{fingerprint}"` — host not yet in the database.
/// - `"changed:{old_fingerprint}:{new_fingerprint}"` — host known but fingerprint differs.
Future<String> checkHostKey(
        {required String host,
        required int port,
        required String fingerprint,
        required String keyType}) =>
    TermexBridge.instance.api.crateApiSshCheckHostKey(
        host: host, port: port, fingerprint: fingerprint, keyType: keyType);

/// Stores an SSH key passphrase in the OS keychain for [server_id]. Used by
/// the Flutter passphrase prompt (P2.3) so encrypted private keys can be
/// unlocked at connect time without requiring the user to re-enter the
/// secret on each reconnect. An empty value deletes the stored entry.
Future<void> sshStorePassphrase(
        {required String serverId, required String passphrase}) =>
    TermexBridge.instance.api.crateApiSshSshStorePassphrase(
        serverId: serverId, passphrase: passphrase);

/// Returns true if a key passphrase is currently stored in the keychain for
/// [server_id]. The value itself is never returned across the bridge.
Future<bool> sshHasPassphrase({required String serverId}) =>
    TermexBridge.instance.api.crateApiSshSshHasPassphrase(serverId: serverId);

/// Adds or updates a host-key entry in the `known_hosts` table.
///
/// Uses `INSERT OR REPLACE` to handle both new hosts and key rotation while
/// preserving the original `first_seen` timestamp.
Future<void> trustHostKey(
        {required String host,
        required int port,
        required String fingerprint,
        required String keyType}) =>
    TermexBridge.instance.api.crateApiSshTrustHostKey(
        host: host, port: port, fingerprint: fingerprint, keyType: keyType);

/// Returns every active entry in the global proxy session pool. Cheap
/// `RwLock<HashMap>` read; safe to poll at high frequency.
Future<List<ProxyPoolStat>> sessionPoolStats() =>
    TermexBridge.instance.api.crateApiSshSessionPoolStats();

/// Drains queued chain-progress events for [session_id]. Polls return any
/// events accumulated since the last call; Flutter calls this on the same
/// timer that already drains `poll_ssh_events`.
Future<List<ChainProgressDto>> pollChainProgress({required String sessionId}) =>
    TermexBridge.instance.api
        .crateApiSshPollChainProgress(sessionId: sessionId);

/// Runs the chain algorithm against an in-memory fake connector that
/// scripts hop outcomes via [hop_failures] — entry `i` is the number of
/// transient failures the i-th hop simulates before succeeding (capped by
/// `max_retries_per_hop = 3`; values higher than 3 cause that hop to
/// permanently fail). Used by the v0.69+ integration tests and the
/// Flutter reconnect-banner demo path; lets the UI exercise the full
/// progress event stream without a real bastion.
Future<void> chainConnectSimulate(
        {required String sessionId,
        required List<ChainHopInfo> hops,
        required List<int> hopFailures,
        required BigInt backoffBaseMs,
        required BigInt backoffMaxMs}) =>
    TermexBridge.instance.api.crateApiSshChainConnectSimulate(
        sessionId: sessionId,
        hops: hops,
        hopFailures: hopFailures,
        backoffBaseMs: backoffBaseMs,
        backoffMaxMs: backoffMaxMs);

/// HopConfig surfaced to Dart — mirrors `termex_core::ssh::chain::HopConfig`
/// but lives here to dodge the FRB orphan-rule restriction on foreign types.
class ChainHopInfo {
  final String hopId;
  final String name;
  final String host;
  final int port;

  const ChainHopInfo({
    required this.hopId,
    required this.name,
    required this.host,
    required this.port,
  });

  @override
  int get hashCode =>
      hopId.hashCode ^ name.hashCode ^ host.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChainHopInfo &&
          runtimeType == other.runtimeType &&
          hopId == other.hopId &&
          name == other.name &&
          host == other.host &&
          port == other.port;
}

/// Snapshot of one entry in the proxy session pool. Surfaces via the debug
/// panel in `about_tab.dart` so users can verify reuse of upstream
/// connections when multiple servers share the same proxy/jump host.
class ProxyPoolStat {
  /// One of `"socks5"` / `"socks4"` / `"http"` / `"tor"` / `"ssh-jump"`.
  final String proxyType;
  final String host;
  final int port;
  final String? username;
  final int refCount;

  /// Unix epoch seconds when the underlying TCP connection was opened.
  final PlatformInt64 connectedSince;
  final PlatformInt64 bytesTransferred;

  const ProxyPoolStat({
    required this.proxyType,
    required this.host,
    required this.port,
    this.username,
    required this.refCount,
    required this.connectedSince,
    required this.bytesTransferred,
  });

  @override
  int get hashCode =>
      proxyType.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      refCount.hashCode ^
      connectedSince.hashCode ^
      bytesTransferred.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyPoolStat &&
          runtimeType == other.runtimeType &&
          proxyType == other.proxyType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          refCount == other.refCount &&
          connectedSince == other.connectedSince &&
          bytesTransferred == other.bytesTransferred;
}

/// Parameters for a transient SSH connection test. Mirrors the add-server
/// form fields so the user can verify credentials before persisting the
/// row to the database.
class SshConnectionTestParams {
  final String host;
  final int port;
  final String username;
  final String authType;
  final String? password;

  /// Path to an on-disk private key file. Used when `key_data` is empty.
  final String? keyPath;

  /// Raw private key contents. Takes precedence over `key_path` when set —
  /// lets the dialog test a pasted key without writing it to disk first.
  final String? keyData;
  final String? keyPassphrase;

  /// v0.79.66: id of the server being edited, if any. When the test
  /// is fired from the Edit-Server dialog and the password / passphrase
  /// fields are left blank (because we never seed them from the OS
  /// keychain into a UI text field — security rule), we fall back to
  /// reading the stored credential from the keychain by this id. Saves
  /// the user from having to re-type their password just to run the
  /// test. None means "create flow" — no keychain fallback.
  final String? existingServerId;

  const SshConnectionTestParams({
    required this.host,
    required this.port,
    required this.username,
    required this.authType,
    this.password,
    this.keyPath,
    this.keyData,
    this.keyPassphrase,
    this.existingServerId,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      authType.hashCode ^
      password.hashCode ^
      keyPath.hashCode ^
      keyData.hashCode ^
      keyPassphrase.hashCode ^
      existingServerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshConnectionTestParams &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          authType == other.authType &&
          password == other.password &&
          keyPath == other.keyPath &&
          keyData == other.keyData &&
          keyPassphrase == other.keyPassphrase &&
          existingServerId == other.existingServerId;
}
