// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../frb_ssh_emitter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect_direct`, `load_connect_row`, `mark_last_connected`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectRow`

/// Opens an SSH session and starts streaming terminal events to a
/// per-session queue that Dart polls via `poll_ssh_events`.
///
/// Scope (v0.50.x): direct TCP connection + password or key auth against
/// the server's stored credentials. Chain-through-bastion and network
/// proxies remain routed through the legacy Tauri path; see
/// `docs/tech-debt.md` T-9 for the follow-up plan.
Future<String> openSshSession(
        {required String serverId, required int cols, required int rows}) =>
    TermexBridge.instance.api
        .crateApiSshOpenSshSession(serverId: serverId, cols: cols, rows: rows);

/// Drains pending events for a session. Called by the Dart polling task.
Future<List<SshStreamEvent>> pollSshEvents({required String sessionId}) =>
    TermexBridge.instance.api.crateApiSshPollSshEvents(sessionId: sessionId);

/// Sends raw bytes to the shell stdin of the given session.
Future<void> writeStdin({required String sessionId, required List<int> data}) =>
    TermexBridge.instance.api
        .crateApiSshWriteStdin(sessionId: sessionId, data: data);

/// Resizes the pseudo-terminal of the given session.
Future<void> resizeTerminal(
        {required String sessionId, required int cols, required int rows}) =>
    TermexBridge.instance.api.crateApiSshResizeTerminal(
        sessionId: sessionId, cols: cols, rows: rows);

/// Closes the shell channel of the given session and removes it from the
/// registry. Idempotent — does nothing if the session is not found.
Future<void> closeSshSession({required String sessionId}) =>
    TermexBridge.instance.api.crateApiSshCloseSshSession(sessionId: sessionId);

/// Checks whether an SSH agent is available by inspecting `SSH_AUTH_SOCK`.
Future<bool> checkSshAgentAvailable() =>
    TermexBridge.instance.api.crateApiSshCheckSshAgentAvailable();

/// Opens a new session to the same server as an existing session.
///
/// v0.50.x: re-resolves the server from its last-connected record. True
/// channel multiplexing over a shared russh handle is tracked in tech
/// debt T-9 and will land with the proxy-chain migration.
Future<String> openSshSessionClone(
        {required String existingSessionId,
        required int cols,
        required int rows}) =>
    TermexBridge.instance.api.crateApiSshOpenSshSessionClone(
        existingSessionId: existingSessionId, cols: cols, rows: rows);

/// Checks the host-key status for a connection by querying the `known_hosts` table.
///
/// Returns one of:
/// - `"trusted"` — fingerprint matches the stored record.
/// - `"new:{fingerprint}"` — host not yet in the database.
/// - `"changed:{old_fingerprint}:{new_fingerprint}"` — host known but fingerprint differs.
Future<String> checkHostKey(
        {required String host,
        required int port,
        required String fingerprint,
        required String keyType}) =>
    TermexBridge.instance.api.crateApiSshCheckHostKey(
        host: host, port: port, fingerprint: fingerprint, keyType: keyType);

/// Adds or updates a host-key entry in the `known_hosts` table.
///
/// Uses `INSERT OR REPLACE` to handle both new hosts and key rotation while
/// preserving the original `first_seen` timestamp.
Future<void> trustHostKey(
        {required String host,
        required int port,
        required String fingerprint,
        required String keyType}) =>
    TermexBridge.instance.api.crateApiSshTrustHostKey(
        host: host, port: port, fingerprint: fingerprint, keyType: keyType);
