// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_ssh_config_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Parses the SSH config file at `path` (defaults to `~/.ssh/config`) and returns
/// a preview of all non-wildcard entries suitable for display in an import dialog.
Future<List<SshConfigPreviewEntry>> previewSshConfigImport({String? path}) =>
    TermexBridge.instance.api
        .crateApiSshConfigPreviewSshConfigImport(path: path);

/// Imports selected SSH config entries as server records.
///
/// - `path`: path to the SSH config file; defaults to `~/.ssh/config`.
/// - `selected_aliases`: only entries whose `host_alias` is in this list are imported.
///
/// Duplicate entries (same host + port + username) are skipped.
Future<SshConfigImportResult> importSshConfig(
        {String? path, required List<String> selectedAliases}) =>
    TermexBridge.instance.api.crateApiSshConfigImportSshConfig(
        path: path, selectedAliases: selectedAliases);

/// Counts for a completed SSH config import.
class SshConfigImportResult {
  /// Number of entries successfully imported.
  final int imported;

  /// Number of entries skipped (already exist or wildcard).
  final int skipped;

  const SshConfigImportResult({
    required this.imported,
    required this.skipped,
  });

  @override
  int get hashCode => imported.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshConfigImportResult &&
          runtimeType == other.runtimeType &&
          imported == other.imported &&
          skipped == other.skipped;
}

/// A preview of a single SSH config entry to be shown before import.
class SshConfigPreviewEntry {
  /// The Host alias from the config file.
  final String hostAlias;

  /// The resolved hostname (may differ from host_alias via HostName directive).
  final String hostname;

  /// SSH port (default 22).
  final int port;

  /// Username for the connection.
  final String username;

  /// Optional path to an identity file.
  final String? identityFile;

  /// Whether this entry uses a wildcard Host pattern.
  final bool isWildcard;

  const SshConfigPreviewEntry({
    required this.hostAlias,
    required this.hostname,
    required this.port,
    required this.username,
    this.identityFile,
    required this.isWildcard,
  });

  @override
  int get hashCode =>
      hostAlias.hashCode ^
      hostname.hashCode ^
      port.hashCode ^
      username.hashCode ^
      identityFile.hashCode ^
      isWildcard.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshConfigPreviewEntry &&
          runtimeType == other.runtimeType &&
          hostAlias == other.hostAlias &&
          hostname == other.hostname &&
          port == other.port &&
          username == other.username &&
          identityFile == other.identityFile &&
          isWildcard == other.isWildcard;
}
