// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Starts the mDNS advertising and listening service on the given `port`.
Future<void> startSyncService({required int port}) =>
    TermexBridge.instance.api.crateApiSyncStartSyncService(port: port);

/// Stops the sync service and releases all resources.
Future<void> stopSyncService() =>
    TermexBridge.instance.api.crateApiSyncStopSyncService();

/// Returns the list of peer devices currently discovered on the local network.
///
/// OSS builds always return an empty list (no real mDNS impl is shipped).
Future<List<DiscoveredDevice>> getDiscoveredDevices() =>
    TermexBridge.instance.api.crateApiSyncGetDiscoveredDevices();

/// Initiates a pairing request to a peer device at `peer_host:peer_port`.
///
/// Returns the pairing token the initiator must use when calling
/// [`confirm_pairing`].
Future<String> initiatePairing(
        {required String peerHost, required int peerPort}) =>
    TermexBridge.instance.api
        .crateApiSyncInitiatePairing(peerHost: peerHost, peerPort: peerPort);

/// Confirms a pairing by submitting the 6-digit code displayed on the peer
/// device. Returns an opaque session token on success.
Future<String> confirmPairing(
        {required String pairingToken, required String code}) =>
    TermexBridge.instance.api
        .crateApiSyncConfirmPairing(pairingToken: pairingToken, code: code);

/// Generates a pairing code for the local (receiver) device.
///
/// Returns `(token, 6-digit code)` so the UI can display the code to the user.
Future<(String, String)> generatePairingCode() =>
    TermexBridge.instance.api.crateApiSyncGeneratePairingCode();

/// Accepts or rejects an incoming pairing `request_id`.
///
/// When `accept` is `true` a new pairing is created and `Some(code)` is
/// returned so the UI can display the confirmation code. When `accept` is
/// `false` returns `Ok(None)`.
Future<String?> respondToPairing(
        {required String requestId, required bool accept}) =>
    TermexBridge.instance.api
        .crateApiSyncRespondToPairing(requestId: requestId, accept: accept);

/// Pulls data from the peer identified by `session_token` and merges it into
/// the local database.
Future<SyncSummary> syncFromPeer(
        {required String sessionToken,
        required bool includeCredentials,
        String? credentialPassword}) =>
    TermexBridge.instance.api.crateApiSyncSyncFromPeer(
        sessionToken: sessionToken,
        includeCredentials: includeCredentials,
        credentialPassword: credentialPassword);

/// Pushes local data to the peer identified by `session_token`.
Future<SyncSummary> syncToPeer(
        {required String sessionToken,
        required bool includeCredentials,
        String? credentialPassword}) =>
    TermexBridge.instance.api.crateApiSyncSyncToPeer(
        sessionToken: sessionToken,
        includeCredentials: includeCredentials,
        credentialPassword: credentialPassword);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DiscoveredDevice>>
abstract class DiscoveredDevice implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncSummary>>
abstract class SyncSummary implements RustOpaqueInterface {}
