// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_state`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Returns the current clipboard text (process-local cache when DB unavailable).
Future<String> clipboardRead() =>
    TermexBridge.instance.api.crateApiSystemClipboardRead();

/// Writes `text` to the process-local clipboard cache.
Future<void> clipboardWrite({required String text}) =>
    TermexBridge.instance.api.crateApiSystemClipboardWrite(text: text);

/// Clears the clipboard cache.
Future<void> clipboardClear() =>
    TermexBridge.instance.api.crateApiSystemClipboardClear();

/// Validates that `url` begins with a recognised scheme.
///
/// Actual launching is handled in the Flutter layer via `url_launcher`; this
/// function is the Rust-side allow-list gate.
Future<bool> urlCanOpen({required String url}) =>
    TermexBridge.instance.api.crateApiSystemUrlCanOpen(url: url);

/// Returns `Ok(())` when the scheme is on the allow-list, `Err` otherwise.
Future<void> urlValidate({required String url}) =>
    TermexBridge.instance.api.crateApiSystemUrlValidate(url: url);

/// Persists window state into the `settings` key-value table.
Future<void> windowStateSave({required WindowState state}) =>
    TermexBridge.instance.api.crateApiSystemWindowStateSave(state: state);

/// Restores window state from the `settings` table.
///
/// Returns a default state when the database is not unlocked or when the keys
/// have never been written.
Future<WindowState> windowStateRestore() =>
    TermexBridge.instance.api.crateApiSystemWindowStateRestore();

/// Clears all persisted window-state keys from the `settings` table.
Future<void> windowStateReset() =>
    TermexBridge.instance.api.crateApiSystemWindowStateReset();

/// Snapshot of the application window's geometry and open tabs.
class WindowState {
  final double width;
  final double height;
  final double x;
  final double y;
  final bool isMaximized;

  /// Server IDs of tabs that were open at last save (no auto-reconnect).
  final List<String> openTabServerIds;

  const WindowState({
    required this.width,
    required this.height,
    required this.x,
    required this.y,
    required this.isMaximized,
    required this.openTabServerIds,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      x.hashCode ^
      y.hashCode ^
      isMaximized.hashCode ^
      openTabServerIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowState &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          x == other.x &&
          y == other.y &&
          isMaximized == other.isMaximized &&
          openTabServerIds == other.openTabServerIds;
}
