// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns `true` if `role` has the `permission` key.
Future<bool> teamHasPermission(
        {required String role, required String permission}) =>
    TermexBridge.instance.api.crateApiTeamPermissionsTeamHasPermission(
        role: role, permission: permission);

/// Lists every permission key the given `role` possesses.
Future<List<String>> teamRolePermissions({required String role}) =>
    TermexBridge.instance.api
        .crateApiTeamPermissionsTeamRolePermissions(role: role);

/// Lists every permission key defined by the matrix, for UI rendering.
Future<List<String>> teamListPermissionKeys() =>
    TermexBridge.instance.api.crateApiTeamPermissionsTeamListPermissionKeys();

/// Lists every role name defined by the matrix.
Future<List<String>> teamListRoles() =>
    TermexBridge.instance.api.crateApiTeamPermissionsTeamListRoles();
