// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `role_from_str`, `role_to_str`, `whoami_placeholder`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WhoAmI`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Returns the list of current team members.
Future<List<TeamMember>> teamGetMembers() =>
    TermexBridge.instance.api.crateApiTeamTeamGetMembers();

/// Adds a new team member (used during invite acceptance and tests).
Future<TeamMember> teamAddMember(
        {required String name,
        required String email,
        required TeamRole role}) =>
    TermexBridge.instance.api
        .crateApiTeamTeamAddMember(name: name, email: email, role: role);

/// Removes a member from the team workspace. Refuses to delete an owner.
Future<void> teamRemoveMember({required String memberId}) =>
    TermexBridge.instance.api.crateApiTeamTeamRemoveMember(memberId: memberId);

/// Updates the role of an existing team member.
///
/// Refuses to demote the last owner — at least one owner must remain.
Future<void> teamUpdateRole(
        {required String memberId, required TeamRole role}) =>
    TermexBridge.instance.api
        .crateApiTeamTeamUpdateRole(memberId: memberId, role: role);

/// Parses an invite code into its component payload.  Returns `Err` if the
/// code is malformed or expired.
Future<TeamInvitePayload> teamInviteDecode({required String code}) =>
    TermexBridge.instance.api.crateApiTeamTeamInviteDecode(code: code);

/// Generates a new invite code for the specified `role`, valid for
/// `expires_hours` hours from now.
Future<TeamInvite> teamInviteGenerate(
        {required TeamRole role, required int expiresHours}) =>
    TermexBridge.instance.api
        .crateApiTeamTeamInviteGenerate(role: role, expiresHours: expiresHours);

/// Accepts an invite code using the team `passphrase` to decrypt the shared
/// workspace key. On success:
///   1. Validates the code's signature + expiry via [team_invite_decode]
///   2. Verifies the passphrase against the keychain-stored team passphrase
///   3. Inserts the caller as a `team_members` row with the invite's role
///   4. Marks the `team_invites` row as accepted (if present)
Future<void> teamInviteAccept(
        {required String code, required String passphrase}) =>
    TermexBridge.instance.api
        .crateApiTeamTeamInviteAccept(code: code, passphrase: passphrase);

/// Returns all unresolved sync conflicts.
///
/// Backed by the `team_pending_conflicts` table — populated by
/// `team::sync::resolve_conflicts` when a user marks a conflict as
/// "skip for now". The returned `TeamConflict.id` is the composite key
/// `{entity_type}:{entity_id}` so callers can route back to the same row.
Future<List<TeamConflict>> teamListConflicts() =>
    TermexBridge.instance.api.crateApiTeamTeamListConflicts();

/// Resolves `conflict_id` by choosing either the local or the remote value.
///
/// For this v0.50.x cut we only delete the pending row — the "apply remote"
/// side is handled by the next full sync cycle, which re-imports remote
/// state as part of `team_sync_now`. This matches the Tauri legacy flow
/// where `Skip → Resolve later` simply removes the pending marker.
Future<void> teamResolveConflict(
        {required String conflictId, required bool useLocal}) =>
    TermexBridge.instance.api.crateApiTeamTeamResolveConflict(
        conflictId: conflictId, useLocal: useLocal);

/// Triggers an immediate sync with the team relay.
///
/// Returns the number of changes applied locally. Delegates to
/// [`termex_core::team::sync`] after verifying that a team repo and key are
/// configured. When `team_repo_path` is absent the call returns 0 silently
/// (no-op for users who haven't enrolled in a team).
Future<int> teamSyncNow() =>
    TermexBridge.instance.api.crateApiTeamTeamSyncNow();

/// Verifies that `passphrase` matches the stored team workspace passphrase.
///
/// The passphrase is kept in the OS keychain under the shared
/// `team_passphrase` entry. This function performs a constant-time
/// comparison to avoid timing side-channels on the passphrase length.
Future<bool> teamVerifyPassphrase({required String passphrase}) =>
    TermexBridge.instance.api
        .crateApiTeamTeamVerifyPassphrase(passphrase: passphrase);

/// Changes the team workspace passphrase.
///
/// `old_passphrase` is verified against the keychain entry; on match the
/// new value replaces it. Remote distribution to other members happens at
/// the next `team_sync_now` which re-encrypts the workspace blob via
/// `termex_core::team::crypto`.
Future<void> teamChangePassphrase(
        {required String oldPassphrase, required String newPassphrase}) =>
    TermexBridge.instance.api.crateApiTeamTeamChangePassphrase(
        oldPassphrase: oldPassphrase, newPassphrase: newPassphrase);

/// A sync conflict between a local and a remote version of a server field.
class TeamConflict {
  final String id;
  final String serverId;

  /// The server field that diverged (e.g. `"host"`, `"port"`).
  final String field;
  final String localValue;
  final String remoteValue;

  const TeamConflict({
    required this.id,
    required this.serverId,
    required this.field,
    required this.localValue,
    required this.remoteValue,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      serverId.hashCode ^
      field.hashCode ^
      localValue.hashCode ^
      remoteValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TeamConflict &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          serverId == other.serverId &&
          field == other.field &&
          localValue == other.localValue &&
          remoteValue == other.remoteValue;
}

/// A one-time invite code that grants access to the team workspace.
class TeamInvite {
  /// Short alphanumeric code to share with the invitee.
  final String code;

  /// ISO 8601 timestamp after which the code is no longer valid.
  final String expiresAt;
  final TeamRole role;

  const TeamInvite({
    required this.code,
    required this.expiresAt,
    required this.role,
  });

  @override
  int get hashCode => code.hashCode ^ expiresAt.hashCode ^ role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TeamInvite &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          expiresAt == other.expiresAt &&
          role == other.role;
}

/// The opaque payload embedded inside a `TeamInvite.code`.  Mirrors the
/// shape documented in v0.46 spec §5.2 (JWT-like, HMAC-signed).
class TeamInvitePayload {
  /// Team identifier (UUID).
  final String teamId;

  /// Role to assign on acceptance.
  final TeamRole role;

  /// Expiration time (RFC3339).
  final String exp;

  /// Nonce to prevent code guessing.
  final String nonce;

  const TeamInvitePayload({
    required this.teamId,
    required this.role,
    required this.exp,
    required this.nonce,
  });

  @override
  int get hashCode =>
      teamId.hashCode ^ role.hashCode ^ exp.hashCode ^ nonce.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TeamInvitePayload &&
          runtimeType == other.runtimeType &&
          teamId == other.teamId &&
          role == other.role &&
          exp == other.exp &&
          nonce == other.nonce;
}

/// A user who belongs to the current team workspace.
class TeamMember {
  final String id;
  final String name;
  final String email;
  final TeamRole role;

  /// ISO 8601 timestamp of when the member joined.
  final String joinedAt;

  const TeamMember({
    required this.id,
    required this.name,
    required this.email,
    required this.role,
    required this.joinedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      email.hashCode ^
      role.hashCode ^
      joinedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TeamMember &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          email == other.email &&
          role == other.role &&
          joinedAt == other.joinedAt;
}

/// Access level of a team member.
enum TeamRole {
  owner,
  admin,
  member,
  viewer,
  ;
}
