// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Generates a QR-code-ready `termex-team://join?…` invite URL and returns it
/// as a UTF-8 string.
///
/// The QR rendering is done on the Dart side via `qr_flutter`; Rust only
/// generates the URL so the crypto token is produced in the trusted boundary.
/// Returns `Err(_)` if `team_id` is unknown or the caller lacks admin rights.
Future<String> generateInviteUrl(
        {required String teamId, required int expiresInHours}) =>
    TermexBridge.instance.api.crateApiTeamMobileGenerateInviteUrl(
        teamId: teamId, expiresInHours: expiresInHours);

/// Parses a raw `termex-team://join?…` string (from a QR scan or clipboard
/// paste) and returns structured invite data.
///
/// Returns `Err(_)` when the scheme is wrong, a required parameter is missing,
/// or the token is expired.
Future<InviteInfo> parseInviteUrl({required String qrContent}) =>
    TermexBridge.instance.api
        .crateApiTeamMobileParseInviteUrl(qrContent: qrContent);

/// Returns true if the team's Git remote is currently reachable.
///
/// Used to decide whether to enter offline mode.  Times out after 5 seconds
/// (callers should add their own `Future.timeout` on the Dart side).
Future<bool> checkTeamRepoReachable({required String teamId}) =>
    TermexBridge.instance.api
        .crateApiTeamMobileCheckTeamRepoReachable(teamId: teamId);

/// Returns the on-disk size of the team's local Git clone in kilobytes.
///
/// Used to warn users when the repository exceeds the recommended 50 MB limit.
/// Returns `Err(_)` if the team has never been cloned locally.
Future<BigInt> getTeamStorageSize({required String teamId}) =>
    TermexBridge.instance.api
        .crateApiTeamMobileGetTeamStorageSize(teamId: teamId);

/// Mobile-only Team Collaboration APIs.
///
/// Supplements the existing `team.rs` FRB module with functions that are
/// specific to mobile — QR invite generation, invite URL parsing, network
/// reachability, and local storage accounting.
///
/// All functions are stubs:  Git / crypto business logic lives in
/// `crates/termex-core/src/team/`; these wrappers will be wired once the
/// iOS/Android cross-compilation chain is validated (v0.58.0 Plan A gate).
/// Parsed content of a `termex-team://join?…` invite URL.
class InviteInfo {
  /// The Git repository URL the invitee should clone.
  final String repoUrl;

  /// Short-lived token used to authenticate the clone request.
  final String token;

  /// Human-readable team name (for display in the join-team sheet).
  final String teamName;

  /// ISO 8601 expiry timestamp.
  final String expiresAt;

  const InviteInfo({
    required this.repoUrl,
    required this.token,
    required this.teamName,
    required this.expiresAt,
  });

  @override
  int get hashCode =>
      repoUrl.hashCode ^
      token.hashCode ^
      teamName.hashCode ^
      expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteInfo &&
          runtimeType == other.runtimeType &&
          repoUrl == other.repoUrl &&
          token == other.token &&
          teamName == other.teamName &&
          expiresAt == other.expiresAt;
}
