// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UpdateChannel`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `as_str`, `parse`

Future<String> appcastUrl({required String channel}) =>
    TermexBridge.instance.api.crateApiUpdateAppcastUrl(channel: channel);

/// Compare semver `a` vs `b`.  Returns 1 if a>b, -1 if a<b, 0 equal.
///
/// Accepts `"0.49.0"` and `"0.49.0-beta.3"` — pre-release is considered
/// lower than release per semver §11.
Future<int> compareVersions({required String a, required String b}) =>
    TermexBridge.instance.api.crateApiUpdateCompareVersions(a: a, b: b);

Future<bool> isUpdateAvailable(
        {required String current, required String remote}) =>
    TermexBridge.instance.api
        .crateApiUpdateIsUpdateAvailable(current: current, remote: remote);

/// Parse a minimal Sparkle-style appcast and return the highest release that
/// is newer than `current_version`.
///
/// Only the fields we need are extracted — this is *not* a general-purpose
/// RSS parser.  Tolerates unknown elements.
Future<UpdateManifest> parseAppcast(
        {required String xml, required String currentVersion}) =>
    TermexBridge.instance.api
        .crateApiUpdateParseAppcast(xml: xml, currentVersion: currentVersion);

Future<UpdateConfig> updateConfigGet() =>
    TermexBridge.instance.api.crateApiUpdateUpdateConfigGet();

Future<UpdateConfig> updateConfigSet(
        {String? channel,
        bool? autoDownload,
        PlatformInt64? checkIntervalHours}) =>
    TermexBridge.instance.api.crateApiUpdateUpdateConfigSet(
        channel: channel,
        autoDownload: autoDownload,
        checkIntervalHours: checkIntervalHours);

Future<void> updateMarkChecked({required String nowRfc3339}) =>
    TermexBridge.instance.api
        .crateApiUpdateUpdateMarkChecked(nowRfc3339: nowRfc3339);

Future<void> testReset() => TermexBridge.instance.api.crateApiUpdateTestReset();

class UpdateConfig {
  final String channel;
  final bool autoDownload;
  final PlatformInt64 checkIntervalHours;
  final String? lastCheckedAt;

  const UpdateConfig({
    required this.channel,
    required this.autoDownload,
    required this.checkIntervalHours,
    this.lastCheckedAt,
  });

  static Future<UpdateConfig> default_() =>
      TermexBridge.instance.api.crateApiUpdateUpdateConfigDefault();

  @override
  int get hashCode =>
      channel.hashCode ^
      autoDownload.hashCode ^
      checkIntervalHours.hashCode ^
      lastCheckedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateConfig &&
          runtimeType == other.runtimeType &&
          channel == other.channel &&
          autoDownload == other.autoDownload &&
          checkIntervalHours == other.checkIntervalHours &&
          lastCheckedAt == other.lastCheckedAt;
}

class UpdateManifest {
  final String currentVersion;
  final String? availableVersion;
  final String? changelogUrl;
  final String? downloadUrl;
  final String? deltaFrom;
  final String? deltaUrl;
  final PlatformInt64? sizeBytes;

  const UpdateManifest({
    required this.currentVersion,
    this.availableVersion,
    this.changelogUrl,
    this.downloadUrl,
    this.deltaFrom,
    this.deltaUrl,
    this.sizeBytes,
  });

  @override
  int get hashCode =>
      currentVersion.hashCode ^
      availableVersion.hashCode ^
      changelogUrl.hashCode ^
      downloadUrl.hashCode ^
      deltaFrom.hashCode ^
      deltaUrl.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateManifest &&
          runtimeType == other.runtimeType &&
          currentVersion == other.currentVersion &&
          availableVersion == other.availableVersion &&
          changelogUrl == other.changelogUrl &&
          downloadUrl == other.downloadUrl &&
          deltaFrom == other.deltaFrom &&
          deltaUrl == other.deltaUrl &&
          sizeBytes == other.sizeBytes;
}
