// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Event delivered to the Flutter side.
///
/// The Dart layer pattern-matches on the `kind` field and extracts the
/// relevant payload. Kept as a flat struct (not a nested enum) so that
/// `flutter_rust_bridge` v2 codegen produces an ergonomic Dart class
/// without union-type gymnastics.
class SshStreamEvent {
  /// One of: `stdout`, `exit`, `disconnected`, `port_forward`.
  final String kind;

  /// Terminal bytes when `kind == "stdout"`. Empty otherwise.
  final Uint8List data;

  /// Exit code when `kind == "exit"`. Zero otherwise.
  final int exitCode;

  /// Named event identifier (port-forward notifications).
  final String event;

  /// Arbitrary JSON payload for `port_forward` events.
  final String payload;

  const SshStreamEvent({
    required this.kind,
    required this.data,
    required this.exitCode,
    required this.event,
    required this.payload,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      data.hashCode ^
      exitCode.hashCode ^
      event.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshStreamEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          data == other.data &&
          exitCode == other.exitCode &&
          event == other.event &&
          payload == other.payload;
}
