// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/ai.dart';
import 'api/app.dart';
import 'api/audit_catalogue.dart';
import 'api/backup.dart';
import 'api/cloud.dart';
import 'api/crypto.dart';
import 'api/external_tools.dart';
import 'api/git_sync.dart';
import 'api/group.dart';
import 'api/keybindings.dart';
import 'api/local_ai.dart';
import 'api/local_fs.dart';
import 'api/monitor.dart';
import 'api/plugin.dart';
import 'api/port_forward.dart';
import 'api/proxy.dart';
import 'api/recording.dart';
import 'api/server.dart';
import 'api/settings.dart';
import 'api/sftp.dart';
import 'api/snippet.dart';
import 'api/ssh.dart';
import 'api/ssh_config.dart';
import 'api/system.dart';
import 'api/team.dart';
import 'api/team_permissions.dart';
import 'api/theme.dart';
import 'api/update.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_sftp_emitter.dart';
import 'frb_ssh_emitter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class TermexBridgeApiImplPlatform
    extends BaseApiImpl<TermexBridgeWire> {
  TermexBridgeApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiChunkDto dco_decode_ai_chunk_dto(dynamic raw);

  @protected
  AiMessageDto dco_decode_ai_message_dto(dynamic raw);

  @protected
  AiProvider dco_decode_ai_provider(dynamic raw);

  @protected
  AiProviderConfig dco_decode_ai_provider_config(dynamic raw);

  @protected
  AppInitState dco_decode_app_init_state(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  AuditLogEntry dco_decode_audit_log_entry(dynamic raw);

  @protected
  AuthType dco_decode_auth_type(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiProviderConfig dco_decode_box_autoadd_ai_provider_config(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CloudCredential dco_decode_box_autoadd_cloud_credential(dynamic raw);

  @protected
  ConflictInfo dco_decode_box_autoadd_conflict_info(dynamic raw);

  @protected
  GitSyncInput dco_decode_box_autoadd_git_sync_input(dynamic raw);

  @protected
  GroupDto dco_decode_box_autoadd_group_dto(dynamic raw);

  @protected
  GroupInput dco_decode_box_autoadd_group_input(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ProxyConfig dco_decode_box_autoadd_proxy_config(dynamic raw);

  @protected
  ServerDto dco_decode_box_autoadd_server_dto(dynamic raw);

  @protected
  ServerInput dco_decode_box_autoadd_server_input(dynamic raw);

  @protected
  ThemeConfig dco_decode_box_autoadd_theme_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  WindowState dco_decode_box_autoadd_window_state(dynamic raw);

  @protected
  CloudCredential dco_decode_cloud_credential(dynamic raw);

  @protected
  CommandHistoryEntry dco_decode_command_history_entry(dynamic raw);

  @protected
  ConflictInfo dco_decode_conflict_info(dynamic raw);

  @protected
  ConversationDto dco_decode_conversation_dto(dynamic raw);

  @protected
  EcsFavorite dco_decode_ecs_favorite(dynamic raw);

  @protected
  ExternalToolStatus dco_decode_external_tool_status(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  ForwardRule dco_decode_forward_rule(dynamic raw);

  @protected
  ForwardStatus dco_decode_forward_status(dynamic raw);

  @protected
  ForwardType dco_decode_forward_type(dynamic raw);

  @protected
  GitSyncHealth dco_decode_git_sync_health(dynamic raw);

  @protected
  GitSyncInput dco_decode_git_sync_input(dynamic raw);

  @protected
  GitSyncMode dco_decode_git_sync_mode(dynamic raw);

  @protected
  GitSyncRepo dco_decode_git_sync_repo(dynamic raw);

  @protected
  GitSyncStatus dco_decode_git_sync_status(dynamic raw);

  @protected
  GroupDto dco_decode_group_dto(dynamic raw);

  @protected
  GroupInput dco_decode_group_input(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  K8sContext dco_decode_k_8_s_context(dynamic raw);

  @protected
  K8sPod dco_decode_k_8_s_pod(dynamic raw);

  @protected
  KeybindingEntry dco_decode_keybinding_entry(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AiChunkDto> dco_decode_list_ai_chunk_dto(dynamic raw);

  @protected
  List<AiMessageDto> dco_decode_list_ai_message_dto(dynamic raw);

  @protected
  List<AuditLogEntry> dco_decode_list_audit_log_entry(dynamic raw);

  @protected
  List<CommandHistoryEntry> dco_decode_list_command_history_entry(dynamic raw);

  @protected
  List<ConversationDto> dco_decode_list_conversation_dto(dynamic raw);

  @protected
  List<EcsFavorite> dco_decode_list_ecs_favorite(dynamic raw);

  @protected
  List<ExternalToolStatus> dco_decode_list_external_tool_status(dynamic raw);

  @protected
  List<ForwardRule> dco_decode_list_forward_rule(dynamic raw);

  @protected
  List<GitSyncRepo> dco_decode_list_git_sync_repo(dynamic raw);

  @protected
  List<GroupDto> dco_decode_list_group_dto(dynamic raw);

  @protected
  List<K8sContext> dco_decode_list_k_8_s_context(dynamic raw);

  @protected
  List<K8sPod> dco_decode_list_k_8_s_pod(dynamic raw);

  @protected
  List<KeybindingEntry> dco_decode_list_keybinding_entry(dynamic raw);

  @protected
  List<LocalFileDto> dco_decode_list_local_file_dto(dynamic raw);

  @protected
  List<LocalModelDto> dco_decode_list_local_model_dto(dynamic raw);

  @protected
  List<PluginDto> dco_decode_list_plugin_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProcessInfo> dco_decode_list_process_info(dynamic raw);

  @protected
  List<ProxyConfig> dco_decode_list_proxy_config(dynamic raw);

  @protected
  List<QuickConnectEntry> dco_decode_list_quick_connect_entry(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<RecordingDto> dco_decode_list_recording_dto(dynamic raw);

  @protected
  List<RecordingEntry> dco_decode_list_recording_entry(dynamic raw);

  @protected
  List<ServerDto> dco_decode_list_server_dto(dynamic raw);

  @protected
  List<SftpFileDto> dco_decode_list_sftp_file_dto(dynamic raw);

  @protected
  List<SftpTransferProgress> dco_decode_list_sftp_transfer_progress(
      dynamic raw);

  @protected
  List<Snippet> dco_decode_list_snippet(dynamic raw);

  @protected
  List<SnippetVariable> dco_decode_list_snippet_variable(dynamic raw);

  @protected
  List<SshConfigPreviewEntry> dco_decode_list_ssh_config_preview_entry(
      dynamic raw);

  @protected
  List<SshStreamEvent> dco_decode_list_ssh_stream_event(dynamic raw);

  @protected
  List<SsmInstance> dco_decode_list_ssm_instance(dynamic raw);

  @protected
  List<TeamConflict> dco_decode_list_team_conflict(dynamic raw);

  @protected
  List<TeamMember> dco_decode_list_team_member(dynamic raw);

  @protected
  LocalAiHealth dco_decode_local_ai_health(dynamic raw);

  @protected
  LocalAiStatus dco_decode_local_ai_status(dynamic raw);

  @protected
  LocalFileDto dco_decode_local_file_dto(dynamic raw);

  @protected
  LocalModelDto dco_decode_local_model_dto(dynamic raw);

  @protected
  MessageRole dco_decode_message_role(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AiProviderConfig? dco_decode_opt_box_autoadd_ai_provider_config(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  CloudCredential? dco_decode_opt_box_autoadd_cloud_credential(dynamic raw);

  @protected
  ConflictInfo? dco_decode_opt_box_autoadd_conflict_info(dynamic raw);

  @protected
  GroupDto? dco_decode_opt_box_autoadd_group_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ProxyConfig? dco_decode_opt_box_autoadd_proxy_config(dynamic raw);

  @protected
  ServerDto? dco_decode_opt_box_autoadd_server_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PermissionCheckResult dco_decode_permission_check_result(dynamic raw);

  @protected
  PluginDto dco_decode_plugin_dto(dynamic raw);

  @protected
  ProcessInfo dco_decode_process_info(dynamic raw);

  @protected
  ProxyConfig dco_decode_proxy_config(dynamic raw);

  @protected
  ProxyType dco_decode_proxy_type(dynamic raw);

  @protected
  QuickConnectEntry dco_decode_quick_connect_entry(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RecordingDto dco_decode_recording_dto(dynamic raw);

  @protected
  RecordingEntry dco_decode_recording_entry(dynamic raw);

  @protected
  ServerDto dco_decode_server_dto(dynamic raw);

  @protected
  ServerInput dco_decode_server_input(dynamic raw);

  @protected
  SftpFileDto dco_decode_sftp_file_dto(dynamic raw);

  @protected
  SftpTransferProgress dco_decode_sftp_transfer_progress(dynamic raw);

  @protected
  Snippet dco_decode_snippet(dynamic raw);

  @protected
  SnippetImportSummary dco_decode_snippet_import_summary(dynamic raw);

  @protected
  SnippetVariable dco_decode_snippet_variable(dynamic raw);

  @protected
  SshConfigImportResult dco_decode_ssh_config_import_result(dynamic raw);

  @protected
  SshConfigPreviewEntry dco_decode_ssh_config_preview_entry(dynamic raw);

  @protected
  SshStreamEvent dco_decode_ssh_stream_event(dynamic raw);

  @protected
  SsmInstance dco_decode_ssm_instance(dynamic raw);

  @protected
  SystemStats dco_decode_system_stats(dynamic raw);

  @protected
  TeamConflict dco_decode_team_conflict(dynamic raw);

  @protected
  TeamInvite dco_decode_team_invite(dynamic raw);

  @protected
  TeamInvitePayload dco_decode_team_invite_payload(dynamic raw);

  @protected
  TeamMember dco_decode_team_member(dynamic raw);

  @protected
  TeamRole dco_decode_team_role(dynamic raw);

  @protected
  ThemeConfig dco_decode_theme_config(dynamic raw);

  @protected
  TorStatus dco_decode_tor_status(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateConfig dco_decode_update_config(dynamic raw);

  @protected
  UpdateManifest dco_decode_update_manifest(dynamic raw);

  @protected
  WindowState dco_decode_window_state(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiChunkDto sse_decode_ai_chunk_dto(SseDeserializer deserializer);

  @protected
  AiMessageDto sse_decode_ai_message_dto(SseDeserializer deserializer);

  @protected
  AiProvider sse_decode_ai_provider(SseDeserializer deserializer);

  @protected
  AiProviderConfig sse_decode_ai_provider_config(SseDeserializer deserializer);

  @protected
  AppInitState sse_decode_app_init_state(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  AuditLogEntry sse_decode_audit_log_entry(SseDeserializer deserializer);

  @protected
  AuthType sse_decode_auth_type(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiProviderConfig sse_decode_box_autoadd_ai_provider_config(
      SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CloudCredential sse_decode_box_autoadd_cloud_credential(
      SseDeserializer deserializer);

  @protected
  ConflictInfo sse_decode_box_autoadd_conflict_info(
      SseDeserializer deserializer);

  @protected
  GitSyncInput sse_decode_box_autoadd_git_sync_input(
      SseDeserializer deserializer);

  @protected
  GroupDto sse_decode_box_autoadd_group_dto(SseDeserializer deserializer);

  @protected
  GroupInput sse_decode_box_autoadd_group_input(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ProxyConfig sse_decode_box_autoadd_proxy_config(SseDeserializer deserializer);

  @protected
  ServerDto sse_decode_box_autoadd_server_dto(SseDeserializer deserializer);

  @protected
  ServerInput sse_decode_box_autoadd_server_input(SseDeserializer deserializer);

  @protected
  ThemeConfig sse_decode_box_autoadd_theme_config(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WindowState sse_decode_box_autoadd_window_state(SseDeserializer deserializer);

  @protected
  CloudCredential sse_decode_cloud_credential(SseDeserializer deserializer);

  @protected
  CommandHistoryEntry sse_decode_command_history_entry(
      SseDeserializer deserializer);

  @protected
  ConflictInfo sse_decode_conflict_info(SseDeserializer deserializer);

  @protected
  ConversationDto sse_decode_conversation_dto(SseDeserializer deserializer);

  @protected
  EcsFavorite sse_decode_ecs_favorite(SseDeserializer deserializer);

  @protected
  ExternalToolStatus sse_decode_external_tool_status(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  ForwardRule sse_decode_forward_rule(SseDeserializer deserializer);

  @protected
  ForwardStatus sse_decode_forward_status(SseDeserializer deserializer);

  @protected
  ForwardType sse_decode_forward_type(SseDeserializer deserializer);

  @protected
  GitSyncHealth sse_decode_git_sync_health(SseDeserializer deserializer);

  @protected
  GitSyncInput sse_decode_git_sync_input(SseDeserializer deserializer);

  @protected
  GitSyncMode sse_decode_git_sync_mode(SseDeserializer deserializer);

  @protected
  GitSyncRepo sse_decode_git_sync_repo(SseDeserializer deserializer);

  @protected
  GitSyncStatus sse_decode_git_sync_status(SseDeserializer deserializer);

  @protected
  GroupDto sse_decode_group_dto(SseDeserializer deserializer);

  @protected
  GroupInput sse_decode_group_input(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  K8sContext sse_decode_k_8_s_context(SseDeserializer deserializer);

  @protected
  K8sPod sse_decode_k_8_s_pod(SseDeserializer deserializer);

  @protected
  KeybindingEntry sse_decode_keybinding_entry(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AiChunkDto> sse_decode_list_ai_chunk_dto(SseDeserializer deserializer);

  @protected
  List<AiMessageDto> sse_decode_list_ai_message_dto(
      SseDeserializer deserializer);

  @protected
  List<AuditLogEntry> sse_decode_list_audit_log_entry(
      SseDeserializer deserializer);

  @protected
  List<CommandHistoryEntry> sse_decode_list_command_history_entry(
      SseDeserializer deserializer);

  @protected
  List<ConversationDto> sse_decode_list_conversation_dto(
      SseDeserializer deserializer);

  @protected
  List<EcsFavorite> sse_decode_list_ecs_favorite(SseDeserializer deserializer);

  @protected
  List<ExternalToolStatus> sse_decode_list_external_tool_status(
      SseDeserializer deserializer);

  @protected
  List<ForwardRule> sse_decode_list_forward_rule(SseDeserializer deserializer);

  @protected
  List<GitSyncRepo> sse_decode_list_git_sync_repo(SseDeserializer deserializer);

  @protected
  List<GroupDto> sse_decode_list_group_dto(SseDeserializer deserializer);

  @protected
  List<K8sContext> sse_decode_list_k_8_s_context(SseDeserializer deserializer);

  @protected
  List<K8sPod> sse_decode_list_k_8_s_pod(SseDeserializer deserializer);

  @protected
  List<KeybindingEntry> sse_decode_list_keybinding_entry(
      SseDeserializer deserializer);

  @protected
  List<LocalFileDto> sse_decode_list_local_file_dto(
      SseDeserializer deserializer);

  @protected
  List<LocalModelDto> sse_decode_list_local_model_dto(
      SseDeserializer deserializer);

  @protected
  List<PluginDto> sse_decode_list_plugin_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProcessInfo> sse_decode_list_process_info(SseDeserializer deserializer);

  @protected
  List<ProxyConfig> sse_decode_list_proxy_config(SseDeserializer deserializer);

  @protected
  List<QuickConnectEntry> sse_decode_list_quick_connect_entry(
      SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<RecordingDto> sse_decode_list_recording_dto(
      SseDeserializer deserializer);

  @protected
  List<RecordingEntry> sse_decode_list_recording_entry(
      SseDeserializer deserializer);

  @protected
  List<ServerDto> sse_decode_list_server_dto(SseDeserializer deserializer);

  @protected
  List<SftpFileDto> sse_decode_list_sftp_file_dto(SseDeserializer deserializer);

  @protected
  List<SftpTransferProgress> sse_decode_list_sftp_transfer_progress(
      SseDeserializer deserializer);

  @protected
  List<Snippet> sse_decode_list_snippet(SseDeserializer deserializer);

  @protected
  List<SnippetVariable> sse_decode_list_snippet_variable(
      SseDeserializer deserializer);

  @protected
  List<SshConfigPreviewEntry> sse_decode_list_ssh_config_preview_entry(
      SseDeserializer deserializer);

  @protected
  List<SshStreamEvent> sse_decode_list_ssh_stream_event(
      SseDeserializer deserializer);

  @protected
  List<SsmInstance> sse_decode_list_ssm_instance(SseDeserializer deserializer);

  @protected
  List<TeamConflict> sse_decode_list_team_conflict(
      SseDeserializer deserializer);

  @protected
  List<TeamMember> sse_decode_list_team_member(SseDeserializer deserializer);

  @protected
  LocalAiHealth sse_decode_local_ai_health(SseDeserializer deserializer);

  @protected
  LocalAiStatus sse_decode_local_ai_status(SseDeserializer deserializer);

  @protected
  LocalFileDto sse_decode_local_file_dto(SseDeserializer deserializer);

  @protected
  LocalModelDto sse_decode_local_model_dto(SseDeserializer deserializer);

  @protected
  MessageRole sse_decode_message_role(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AiProviderConfig? sse_decode_opt_box_autoadd_ai_provider_config(
      SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CloudCredential? sse_decode_opt_box_autoadd_cloud_credential(
      SseDeserializer deserializer);

  @protected
  ConflictInfo? sse_decode_opt_box_autoadd_conflict_info(
      SseDeserializer deserializer);

  @protected
  GroupDto? sse_decode_opt_box_autoadd_group_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ProxyConfig? sse_decode_opt_box_autoadd_proxy_config(
      SseDeserializer deserializer);

  @protected
  ServerDto? sse_decode_opt_box_autoadd_server_dto(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PermissionCheckResult sse_decode_permission_check_result(
      SseDeserializer deserializer);

  @protected
  PluginDto sse_decode_plugin_dto(SseDeserializer deserializer);

  @protected
  ProcessInfo sse_decode_process_info(SseDeserializer deserializer);

  @protected
  ProxyConfig sse_decode_proxy_config(SseDeserializer deserializer);

  @protected
  ProxyType sse_decode_proxy_type(SseDeserializer deserializer);

  @protected
  QuickConnectEntry sse_decode_quick_connect_entry(
      SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  RecordingDto sse_decode_recording_dto(SseDeserializer deserializer);

  @protected
  RecordingEntry sse_decode_recording_entry(SseDeserializer deserializer);

  @protected
  ServerDto sse_decode_server_dto(SseDeserializer deserializer);

  @protected
  ServerInput sse_decode_server_input(SseDeserializer deserializer);

  @protected
  SftpFileDto sse_decode_sftp_file_dto(SseDeserializer deserializer);

  @protected
  SftpTransferProgress sse_decode_sftp_transfer_progress(
      SseDeserializer deserializer);

  @protected
  Snippet sse_decode_snippet(SseDeserializer deserializer);

  @protected
  SnippetImportSummary sse_decode_snippet_import_summary(
      SseDeserializer deserializer);

  @protected
  SnippetVariable sse_decode_snippet_variable(SseDeserializer deserializer);

  @protected
  SshConfigImportResult sse_decode_ssh_config_import_result(
      SseDeserializer deserializer);

  @protected
  SshConfigPreviewEntry sse_decode_ssh_config_preview_entry(
      SseDeserializer deserializer);

  @protected
  SshStreamEvent sse_decode_ssh_stream_event(SseDeserializer deserializer);

  @protected
  SsmInstance sse_decode_ssm_instance(SseDeserializer deserializer);

  @protected
  SystemStats sse_decode_system_stats(SseDeserializer deserializer);

  @protected
  TeamConflict sse_decode_team_conflict(SseDeserializer deserializer);

  @protected
  TeamInvite sse_decode_team_invite(SseDeserializer deserializer);

  @protected
  TeamInvitePayload sse_decode_team_invite_payload(
      SseDeserializer deserializer);

  @protected
  TeamMember sse_decode_team_member(SseDeserializer deserializer);

  @protected
  TeamRole sse_decode_team_role(SseDeserializer deserializer);

  @protected
  ThemeConfig sse_decode_theme_config(SseDeserializer deserializer);

  @protected
  TorStatus sse_decode_tor_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateConfig sse_decode_update_config(SseDeserializer deserializer);

  @protected
  UpdateManifest sse_decode_update_manifest(SseDeserializer deserializer);

  @protected
  WindowState sse_decode_window_state(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_chunk_dto(AiChunkDto self, SseSerializer serializer);

  @protected
  void sse_encode_ai_message_dto(AiMessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_ai_provider(AiProvider self, SseSerializer serializer);

  @protected
  void sse_encode_ai_provider_config(
      AiProviderConfig self, SseSerializer serializer);

  @protected
  void sse_encode_app_init_state(AppInitState self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_audit_log_entry(AuditLogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_auth_type(AuthType self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_provider_config(
      AiProviderConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(
      AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cloud_credential(
      CloudCredential self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_conflict_info(
      ConflictInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_git_sync_input(
      GitSyncInput self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_group_dto(
      GroupDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_group_input(
      GroupInput self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_proxy_config(
      ProxyConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_server_dto(
      ServerDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_server_input(
      ServerInput self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_theme_config(
      ThemeConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_window_state(
      WindowState self, SseSerializer serializer);

  @protected
  void sse_encode_cloud_credential(
      CloudCredential self, SseSerializer serializer);

  @protected
  void sse_encode_command_history_entry(
      CommandHistoryEntry self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_info(ConflictInfo self, SseSerializer serializer);

  @protected
  void sse_encode_conversation_dto(
      ConversationDto self, SseSerializer serializer);

  @protected
  void sse_encode_ecs_favorite(EcsFavorite self, SseSerializer serializer);

  @protected
  void sse_encode_external_tool_status(
      ExternalToolStatus self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_forward_rule(ForwardRule self, SseSerializer serializer);

  @protected
  void sse_encode_forward_status(ForwardStatus self, SseSerializer serializer);

  @protected
  void sse_encode_forward_type(ForwardType self, SseSerializer serializer);

  @protected
  void sse_encode_git_sync_health(GitSyncHealth self, SseSerializer serializer);

  @protected
  void sse_encode_git_sync_input(GitSyncInput self, SseSerializer serializer);

  @protected
  void sse_encode_git_sync_mode(GitSyncMode self, SseSerializer serializer);

  @protected
  void sse_encode_git_sync_repo(GitSyncRepo self, SseSerializer serializer);

  @protected
  void sse_encode_git_sync_status(GitSyncStatus self, SseSerializer serializer);

  @protected
  void sse_encode_group_dto(GroupDto self, SseSerializer serializer);

  @protected
  void sse_encode_group_input(GroupInput self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_k_8_s_context(K8sContext self, SseSerializer serializer);

  @protected
  void sse_encode_k_8_s_pod(K8sPod self, SseSerializer serializer);

  @protected
  void sse_encode_keybinding_entry(
      KeybindingEntry self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_chunk_dto(
      List<AiChunkDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_message_dto(
      List<AiMessageDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audit_log_entry(
      List<AuditLogEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_command_history_entry(
      List<CommandHistoryEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conversation_dto(
      List<ConversationDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ecs_favorite(
      List<EcsFavorite> self, SseSerializer serializer);

  @protected
  void sse_encode_list_external_tool_status(
      List<ExternalToolStatus> self, SseSerializer serializer);

  @protected
  void sse_encode_list_forward_rule(
      List<ForwardRule> self, SseSerializer serializer);

  @protected
  void sse_encode_list_git_sync_repo(
      List<GitSyncRepo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_group_dto(List<GroupDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_k_8_s_context(
      List<K8sContext> self, SseSerializer serializer);

  @protected
  void sse_encode_list_k_8_s_pod(List<K8sPod> self, SseSerializer serializer);

  @protected
  void sse_encode_list_keybinding_entry(
      List<KeybindingEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_local_file_dto(
      List<LocalFileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_local_model_dto(
      List<LocalModelDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_plugin_dto(
      List<PluginDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_process_info(
      List<ProcessInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_proxy_config(
      List<ProxyConfig> self, SseSerializer serializer);

  @protected
  void sse_encode_list_quick_connect_entry(
      List<QuickConnectEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_recording_dto(
      List<RecordingDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_recording_entry(
      List<RecordingEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_server_dto(
      List<ServerDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sftp_file_dto(
      List<SftpFileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sftp_transfer_progress(
      List<SftpTransferProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_list_snippet(List<Snippet> self, SseSerializer serializer);

  @protected
  void sse_encode_list_snippet_variable(
      List<SnippetVariable> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ssh_config_preview_entry(
      List<SshConfigPreviewEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ssh_stream_event(
      List<SshStreamEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ssm_instance(
      List<SsmInstance> self, SseSerializer serializer);

  @protected
  void sse_encode_list_team_conflict(
      List<TeamConflict> self, SseSerializer serializer);

  @protected
  void sse_encode_list_team_member(
      List<TeamMember> self, SseSerializer serializer);

  @protected
  void sse_encode_local_ai_health(LocalAiHealth self, SseSerializer serializer);

  @protected
  void sse_encode_local_ai_status(LocalAiStatus self, SseSerializer serializer);

  @protected
  void sse_encode_local_file_dto(LocalFileDto self, SseSerializer serializer);

  @protected
  void sse_encode_local_model_dto(LocalModelDto self, SseSerializer serializer);

  @protected
  void sse_encode_message_role(MessageRole self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ai_provider_config(
      AiProviderConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cloud_credential(
      CloudCredential? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_conflict_info(
      ConflictInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_group_dto(
      GroupDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_proxy_config(
      ProxyConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_server_dto(
      ServerDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_permission_check_result(
      PermissionCheckResult self, SseSerializer serializer);

  @protected
  void sse_encode_plugin_dto(PluginDto self, SseSerializer serializer);

  @protected
  void sse_encode_process_info(ProcessInfo self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_config(ProxyConfig self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_type(ProxyType self, SseSerializer serializer);

  @protected
  void sse_encode_quick_connect_entry(
      QuickConnectEntry self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_recording_dto(RecordingDto self, SseSerializer serializer);

  @protected
  void sse_encode_recording_entry(
      RecordingEntry self, SseSerializer serializer);

  @protected
  void sse_encode_server_dto(ServerDto self, SseSerializer serializer);

  @protected
  void sse_encode_server_input(ServerInput self, SseSerializer serializer);

  @protected
  void sse_encode_sftp_file_dto(SftpFileDto self, SseSerializer serializer);

  @protected
  void sse_encode_sftp_transfer_progress(
      SftpTransferProgress self, SseSerializer serializer);

  @protected
  void sse_encode_snippet(Snippet self, SseSerializer serializer);

  @protected
  void sse_encode_snippet_import_summary(
      SnippetImportSummary self, SseSerializer serializer);

  @protected
  void sse_encode_snippet_variable(
      SnippetVariable self, SseSerializer serializer);

  @protected
  void sse_encode_ssh_config_import_result(
      SshConfigImportResult self, SseSerializer serializer);

  @protected
  void sse_encode_ssh_config_preview_entry(
      SshConfigPreviewEntry self, SseSerializer serializer);

  @protected
  void sse_encode_ssh_stream_event(
      SshStreamEvent self, SseSerializer serializer);

  @protected
  void sse_encode_ssm_instance(SsmInstance self, SseSerializer serializer);

  @protected
  void sse_encode_system_stats(SystemStats self, SseSerializer serializer);

  @protected
  void sse_encode_team_conflict(TeamConflict self, SseSerializer serializer);

  @protected
  void sse_encode_team_invite(TeamInvite self, SseSerializer serializer);

  @protected
  void sse_encode_team_invite_payload(
      TeamInvitePayload self, SseSerializer serializer);

  @protected
  void sse_encode_team_member(TeamMember self, SseSerializer serializer);

  @protected
  void sse_encode_team_role(TeamRole self, SseSerializer serializer);

  @protected
  void sse_encode_theme_config(ThemeConfig self, SseSerializer serializer);

  @protected
  void sse_encode_tor_status(TorStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_config(UpdateConfig self, SseSerializer serializer);

  @protected
  void sse_encode_update_manifest(
      UpdateManifest self, SseSerializer serializer);

  @protected
  void sse_encode_window_state(WindowState self, SseSerializer serializer);
}

// Section: wire_class

class TermexBridgeWire implements BaseWire {
  TermexBridgeWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external TermexBridgeWasmModule get wasmModule;

@JS()
@anonymous
extension type TermexBridgeWasmModule._(JSObject _) implements JSObject {}
